"""
LLM narrative generation and concordance analysis.

Holds the prompt templates, the multi-model narrative fan-out, and the
cross-model concordance pass.  Extracted from interpret.py: this layer consumes
the assembled context text (a plain string produced by the analysis layer) and
talks to the LLM endpoints — it references no DB or dose-response-analysis names,
which is why it forms a clean cut with zero external importers.
"""

import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

import requests

from knowledge_base.extract import OllamaEndpoint, LOCAL_OLLAMA
from llm_endpoints import AnthropicEndpoint


# ---------------------------------------------------------------------------
# NarrativeRun — result of a single LLM narrative generation
# ---------------------------------------------------------------------------

@dataclass
class NarrativeRun:
    model: str
    endpoint_name: str
    run_index: int
    narrative: str
    elapsed_seconds: float


# ---------------------------------------------------------------------------
# LLM Synthesis
# ---------------------------------------------------------------------------

INTERPRETATION_SYSTEM = """You are a toxicogenomics expert analyst. You interpret dose-response
gene expression data (BMD analysis results) to predict organism-level and organ-level effects.

Your interpretations are grounded in the scientific literature and biological pathway knowledge
provided to you. You cite specific genes, pathways, and papers to support your conclusions.

You write in a clear, professional scientific style suitable for a regulatory toxicology report."""

INTERPRETATION_PROMPT = """Based on the following dose-response analysis results and literature context,
generate a comprehensive interpretation report.

{context}

---

Please generate a detailed interpretation covering these sections:

## 1. Biological Response Narrative
What biological processes are activated or suppressed at each dose level?
Order your narrative from lowest to highest dose, describing the progression of effects.

## 2. Organ-Level Prediction
Which organs are most likely affected by this exposure? Explain why based on the
gene expression patterns, organ-specific gene annotations, and literature evidence.

## 3. Mechanism of Action
Based on the enriched pathways and GO terms, what is the likely mechanism of toxicity?
Describe the molecular initiating event and key events in the adverse outcome pathway.

## 4. Protective vs. Adverse Responses
Distinguish between adaptive/protective responses (e.g., NRF2 antioxidant defense,
DNA repair, UPR) and responses indicating damage (e.g., apoptosis, inflammation,
fibrosis). At what dose does the transition from adaptive to adverse likely occur?

## 5. Literature Support
For each major conclusion, cite the specific papers and claims from the knowledge base
that support it. Note where your conclusions agree with or extend the literature.

## 6. Confidence Assessment
Rate your confidence in each major conclusion. Note which genes have strong literature
support (consensus genes) vs. those with limited evidence. Identify any novel findings
not well-represented in the existing literature."""


CONCORDANCE_SYSTEM = """You are a meta-analyst comparing multiple independent AI-generated \
toxicogenomics interpretations. Your task is to identify where different models agree, \
disagree, or produce unique insights. You are rigorous, balanced, and cite specific \
model outputs to support your conclusions."""

CONCORDANCE_PROMPT = """Below are {n_narratives} independent toxicogenomics interpretation \
narratives generated by {n_models} different AI models ({n_runs} runs each). Each narrative \
covers the same dose-response dataset but was generated independently.

{narratives_block}

---

Please perform a concordance analysis comparing these narratives across all 6 sections. \
For each section, identify what the models agree on, where they diverge, and any unique insights.

## 1. Biological Response Narrative — Concordance
- **Agreement**: What biological processes/dose-response patterns do most models identify?
- **Divergence**: Where do models disagree on processes, ordering, or significance?
- **Concordance rating**: (Strong / Moderate / Weak agreement)

## 2. Organ-Level Prediction — Concordance
- **Agreement**: Which organ predictions are consistent across models?
- **Divergence**: Where do organ predictions differ?
- **Concordance rating**: (Strong / Moderate / Weak agreement)

## 3. Mechanism of Action — Concordance
- **Agreement**: What molecular mechanisms are consistently identified?
- **Divergence**: Where do mechanistic explanations differ?
- **Concordance rating**: (Strong / Moderate / Weak agreement)

## 4. Protective vs. Adverse Responses — Concordance
- **Agreement**: Do models agree on the adaptive-to-adverse transition dose?
- **Divergence**: Where do models differ on protective vs. adverse classification?
- **Concordance rating**: (Strong / Moderate / Weak agreement)

## 5. Literature Support — Concordance
- **Agreement**: Which papers/claims are cited consistently across models?
- **Divergence**: Are there contradictory literature interpretations?
- **Concordance rating**: (Strong / Moderate / Weak agreement)

## 6. Confidence Assessment — Concordance
- **Agreement**: Do models agree on which findings are high vs. low confidence?
- **Divergence**: Where do confidence assessments differ?
- **Concordance rating**: (Strong / Moderate / Weak agreement)

## High-Confidence Findings
Claims or conclusions supported by 4 or more of the {n_models} models. These represent \
the most robust findings from this analysis.

## Divergent Findings
Claims where models meaningfully disagree. Explain the nature of each disagreement.

## Model-Specific Observations
Unique insights contributed by individual models that others did not identify. \
Note which model produced each observation.

## Overall Concordance Summary
Provide a brief overall assessment of how well the models agree, which sections show \
the strongest consensus, and which would benefit from further investigation."""


def synthesize_interpretation(
    context: str,
    endpoint: OllamaEndpoint | None = None,
) -> str:
    """Send the assembled context to the LLM for narrative synthesis."""
    if endpoint is None:
        endpoint = LOCAL_OLLAMA

    if not endpoint.is_available():
        print(f"  [WARNING] Ollama endpoint {endpoint.name} not available.")
        print("  Skipping LLM synthesis — returning structured context only.")
        return (
            "# Dose-Response Interpretation\n\n"
            "*LLM synthesis unavailable — structured analysis below.*\n\n"
            "```\n" + context + "\n```"
        )

    print(f"  Generating interpretation via {endpoint.name} ({endpoint.model})...")
    prompt = INTERPRETATION_PROMPT.format(context=context)

    # Use higher token limit for interpretation
    payload = {
        "model": endpoint.model,
        "prompt": prompt,
        "system": INTERPRETATION_SYSTEM,
        "stream": False,
        "options": {
            "temperature": 0.3,
            "num_predict": 4096,
        },
    }

    try:
        r = requests.post(
            f"{endpoint.url}/api/generate",
            json=payload,
            timeout=300,
        )
        r.raise_for_status()
        response = r.json().get("response", "")
        if response:
            return f"# Dose-Response Interpretation\n\n{response}"
        else:
            return (
                "# Dose-Response Interpretation\n\n"
                "*LLM returned empty response — structured analysis below.*\n\n"
                "```\n" + context + "\n```"
            )
    except Exception as e:
        print(f"  [ERROR] LLM synthesis failed: {e}")
        return (
            "# Dose-Response Interpretation\n\n"
            f"*LLM synthesis failed ({e}) — structured analysis below.*\n\n"
            "```\n" + context + "\n```"
        )


# ---------------------------------------------------------------------------
# Multi-model narrative generation
# ---------------------------------------------------------------------------

# Model-to-endpoint mapping
MODEL_ENDPOINTS = {
    "qwen2.5:14b": LOCAL_OLLAMA,
    "gemma2:9b": OllamaEndpoint(
        name="remote-6900xt",
        url="http://localhost:11435",
        model="gemma2:9b",
        weight=1,
    ),
    # Claude models resolved dynamically via AnthropicEndpoint
}


def _resolve_endpoint(model: str) -> OllamaEndpoint | AnthropicEndpoint:
    """Return the appropriate endpoint for a model name."""
    if model in MODEL_ENDPOINTS:
        return MODEL_ENDPOINTS[model]
    if model.startswith("claude-"):
        return AnthropicEndpoint(name=f"anthropic-{model}", model=model)
    # Fall back: try local Ollama with the model name overridden
    ep = OllamaEndpoint(
        name=LOCAL_OLLAMA.name,
        url=LOCAL_OLLAMA.url,
        model=model,
        weight=LOCAL_OLLAMA.weight,
    )
    return ep


def _ensure_model_pulled(endpoint: OllamaEndpoint) -> None:
    """Check if model is available on an Ollama endpoint; pull if missing."""
    try:
        r = requests.get(f"{endpoint.url}/api/tags", timeout=10)
        r.raise_for_status()
        models = [m["name"] for m in r.json().get("models", [])]
        # Ollama tags may include `:latest` suffix
        target = endpoint.model
        if any(target == m or target == m.split(":")[0] or m.startswith(target) for m in models):
            print(f"  [{endpoint.name}] Model {target} already present.")
            return
    except requests.RequestException as e:
        print(f"  [WARNING] Cannot check models on {endpoint.name}: {e}")
        return

    print(f"  [{endpoint.name}] Pulling {target}...")
    try:
        r = requests.post(
            f"{endpoint.url}/api/pull",
            json={"name": target, "stream": False},
            timeout=600,
        )
        r.raise_for_status()
        print(f"  [{endpoint.name}] Pull complete for {target}.")
    except requests.RequestException as e:
        print(f"  [WARNING] Pull failed for {target} on {endpoint.name}: {e}")


def generate_narrative(
    context: str,
    endpoint: OllamaEndpoint | AnthropicEndpoint,
    model_override: str | None = None,
    temperature: float = 0.3,
) -> tuple[str, float]:
    """
    Generate a single narrative from the given endpoint.
    Returns (narrative_text, elapsed_seconds).
    """
    prompt = INTERPRETATION_PROMPT.format(context=context)
    start = time.time()

    if isinstance(endpoint, AnthropicEndpoint):
        text = endpoint.generate(prompt, system=INTERPRETATION_SYSTEM,
                                 temperature=temperature)
    elif isinstance(endpoint, OllamaEndpoint):
        # Temporarily override model if needed
        original_model = endpoint.model
        if model_override:
            endpoint.model = model_override
        payload = {
            "model": endpoint.model,
            "prompt": prompt,
            "system": INTERPRETATION_SYSTEM,
            "stream": False,
            "options": {
                "temperature": temperature,
                "num_predict": 4096,
            },
        }
        try:
            r = requests.post(
                f"{endpoint.url}/api/generate",
                json=payload,
                timeout=300,
            )
            r.raise_for_status()
            text = r.json().get("response", "")
        except requests.RequestException as e:
            text = f"[ERROR] Generation failed: {e}"
        finally:
            endpoint.model = original_model
    else:
        text = "[ERROR] Unknown endpoint type"

    elapsed = time.time() - start
    return text, elapsed


def _sanitize_model_name(model: str) -> str:
    """Convert model name to a safe filename component (e.g. qwen2.5:14b -> qwen2.5-14b)."""
    return model.replace(":", "-").replace("/", "-")


def _write_per_model_output(
    runs: list[NarrativeRun],
    model: str,
    base_md: str,
) -> None:
    """Write per-model .md file as each model's runs complete."""
    safe = _sanitize_model_name(model)
    md_path = Path(base_md)
    model_md = md_path.parent / f"{md_path.stem}_{safe}{md_path.suffix}"

    # Build markdown content
    lines = [f"# Narratives: {model}\n"]
    for run in runs:
        lines.append(f"## Run {run.run_index + 1} ({run.elapsed_seconds:.1f}s)\n")
        lines.append(run.narrative)
        lines.append("\n---\n")
    md_text = "\n".join(lines)
    model_md.parent.mkdir(parents=True, exist_ok=True)
    model_md.write_text(md_text)
    print(f"  Saved {model_md}")


def generate_all_narratives(
    context: str,
    models: list[str],
    n_runs: int = 3,
    base_md: str = "output/interpretation.md",
) -> list[NarrativeRun]:
    """
    Generate narratives from multiple models in parallel.
    Each model runs sequentially for n_runs, but models run concurrently.
    Per-model outputs are written as each model completes.
    """
    all_runs: list[NarrativeRun] = []
    lock = __import__("threading").Lock()

    # Pre-flight: ensure Ollama models are pulled
    for model in models:
        ep = _resolve_endpoint(model)
        if isinstance(ep, OllamaEndpoint):
            _ensure_model_pulled(ep)

    def _run_model(model: str) -> list[NarrativeRun]:
        ep = _resolve_endpoint(model)

        # Check availability
        if not ep.is_available():
            print(f"  [WARNING] {model} endpoint not available, skipping.")
            return []

        runs = []
        for i in range(n_runs):
            print(f"  [{model}] Starting run {i + 1}/{n_runs}...")
            text, elapsed = generate_narrative(context, ep, temperature=0.3)
            run = NarrativeRun(
                model=model,
                endpoint_name=ep.name,
                run_index=i,
                narrative=text,
                elapsed_seconds=elapsed,
            )
            runs.append(run)
            print(f"  [{model}] Run {i + 1} done in {elapsed:.1f}s")

        # Write per-model output as soon as this model finishes
        if runs:
            _write_per_model_output(runs, model, base_md)

        with lock:
            all_runs.extend(runs)
        return runs

    # One thread per model — all run concurrently
    with ThreadPoolExecutor(max_workers=len(models)) as executor:
        futures = {executor.submit(_run_model, m): m for m in models}
        for future in as_completed(futures):
            model = futures[future]
            try:
                future.result()
            except Exception as e:
                print(f"  [ERROR] {model} failed: {e}")

    return all_runs


# ---------------------------------------------------------------------------
# Concordance analysis
# ---------------------------------------------------------------------------

def run_concordance_analysis(
    narrative_runs: list[NarrativeRun],
    concordance_model: str = "claude-sonnet-4-6",
) -> tuple[str, str]:
    """
    Analyze concordance across narrative runs.
    Returns (concordance_text, model_used).
    """
    # Group runs by model
    from collections import OrderedDict
    model_runs: dict[str, list[NarrativeRun]] = OrderedDict()
    for run in narrative_runs:
        model_runs.setdefault(run.model, []).append(run)

    models = list(model_runs.keys())
    n_models = len(models)
    n_runs = max((len(runs) for runs in model_runs.values()), default=0)

    # Build narratives block with clear delimiters
    blocks = []
    for run in narrative_runs:
        blocks.append(
            f"### Model: {run.model} — Run {run.run_index + 1}\n\n"
            f"{run.narrative}"
        )
    narratives_block = "\n\n---\n\n".join(blocks)

    prompt = CONCORDANCE_PROMPT.format(
        n_narratives=len(narrative_runs),
        n_models=n_models,
        n_runs=n_runs,
        narratives_block=narratives_block,
    )

    endpoint = _resolve_endpoint(concordance_model)
    if not endpoint.is_available():
        return (
            f"[Concordance analysis unavailable — {concordance_model} endpoint not reachable]",
            concordance_model,
        )

    print(f"  Concordance model: {concordance_model} via {endpoint.name}")
    start = time.time()

    if isinstance(endpoint, AnthropicEndpoint):
        # Concordance needs more tokens than a single narrative (15 narratives → long output)
        old_max = endpoint.max_tokens
        endpoint.max_tokens = 16384
        text = endpoint.generate(prompt, system=CONCORDANCE_SYSTEM, temperature=0.3)
        endpoint.max_tokens = old_max
    elif isinstance(endpoint, OllamaEndpoint):
        payload = {
            "model": endpoint.model,
            "prompt": prompt,
            "system": CONCORDANCE_SYSTEM,
            "stream": False,
            "options": {
                "temperature": 0.3,
                "num_predict": 4096,
            },
        }
        try:
            r = requests.post(
                f"{endpoint.url}/api/generate",
                json=payload,
                timeout=600,
            )
            r.raise_for_status()
            text = r.json().get("response", "")
        except requests.RequestException as e:
            text = f"[ERROR] Concordance generation failed: {e}"
    else:
        text = "[ERROR] Unknown endpoint type for concordance"

    elapsed = time.time() - start
    print(f"  Concordance analysis complete in {elapsed:.1f}s")
    return text, concordance_model
