"""
LLM prompt assembly for the Materials & Methods section.

The methods narrative is generated by feeding the LLM a system prompt
(role + behavior) and a user prompt (structured study context + the
list of subsections to write).  This module composes both.

Public functions:

  - build_subsection_skeleton(ctx)
      Filter SUBSECTION_SKELETON by the MethodsContext flags to produce
      the ordered list of (key, heading_text, heading_level) tuples
      that should appear in the report.  Conditional subsections
      (Transcriptomics, Clinical Pathology, etc.) drop out when the
      relevant data domain isn't present in the pool.

  - build_methods_prompt(ctx)
      Build the (system_prompt, user_prompt) pair.  The system prompt
      pins style + length + tone; the user prompt embeds the study
      context as labelled key-value lines plus the subsection list and
      per-subsection guidelines from _build_subsection_guidelines.

  - _build_subsection_guidelines(ctx, sub_keys)
      Per-subsection "what the LLM should say here" hints, used by
      build_methods_prompt.  Generated from MethodsContext so the
      guideline values stay in sync with the actual data the prompt
      will receive.

Pulled out of methods_report.py so the prompt-construction surface
lives apart from the data extractor and the narrative builders.
methods_report.py re-exports each name so external call sites
(llm_routes uses build_subsection_skeleton + build_methods_prompt
together) keep working.
"""

# ---------------------------------------------------------------------------
# Imports
# ---------------------------------------------------------------------------

from __future__ import annotations

from methods_models import MethodsContext, SUBSECTION_SKELETON


# ---------------------------------------------------------------------------
# Subsection skeleton: which subsections to include given the context
# ---------------------------------------------------------------------------

def build_subsection_skeleton(ctx: MethodsContext) -> list[tuple[str, str, int]]:
    """
    Determine which M&M subsections to include based on domain presence.

    Returns a list of (subsection_key, heading_text, heading_level) tuples
    in the correct order for both the LLM prompt and the rendered report.

    Args:
        ctx: MethodsContext with domain presence flags set.

    Returns:
        Filtered list of subsections that apply to this study.
    """
    skeleton = []
    for key, heading, level, condition in SUBSECTION_SKELETON:
        if condition is None:
            # Always included
            skeleton.append((key, heading, level))
        else:
            # Check the condition field on MethodsContext
            if getattr(ctx, condition, False):
                skeleton.append((key, heading, level))
    return skeleton


# ---------------------------------------------------------------------------
# LLM prompt builder
# ---------------------------------------------------------------------------

def build_methods_prompt(ctx: MethodsContext) -> tuple[str, str]:
    """
    Build the structured LLM prompt for M&M generation.

    Returns (system_prompt, user_prompt) strings.

    The user prompt includes all extracted study context and asks the LLM
    to return a JSON object keyed by subsection key.  Only keys for
    present domains are requested.

    Args:
        ctx: Populated MethodsContext.

    Returns:
        Tuple of (system_prompt, user_prompt).
    """
    system = (
        "You are a toxicology report writer specializing in NTP/NIEHS-style "
        "technical reports for 5-day genomic dose-response studies. "
        "Write precise, formal scientific text. "
        "Return ONLY valid JSON with no markdown formatting."
    )

    # Build the study context block with actual data
    dose_str = ", ".join(str(d) for d in ctx.dose_groups) if ctx.dose_groups else "not specified"
    sexes_str = " and ".join(ctx.sexes) if ctx.sexes else "male and female"

    context_block = f"""## Study Context
- Chemical: {ctx.chemical_name} (CASRN: {ctx.casrn}, DTXSID: {ctx.dtxsid})
- Species: {ctx.species} rats
- Sexes: {sexes_str}
- Route of administration: oral {ctx.route}
- Vehicle: {ctx.vehicle}
- Duration: {ctx.duration_days} days
- Dose groups ({ctx.dose_unit}): {dose_str}
- Animals per treatment group: {ctx.n_per_group} {sexes_str} per dose
- Animals in vehicle control: {ctx.n_control} {sexes_str}"""

    if ctx.n_biosampling > 0:
        context_block += f"\n- Biosampling animals: {ctx.n_biosampling} total"

    # Domain-specific context
    if ctx.has_organ_weights and ctx.organ_weight_endpoints:
        context_block += f"\n- Organs weighed: {', '.join(ctx.organ_weight_endpoints)}"
    if ctx.has_clin_chem and ctx.clin_chem_endpoints:
        context_block += f"\n- Clinical chemistry parameters: {', '.join(ctx.clin_chem_endpoints)}"
    if ctx.has_hematology and ctx.hematology_endpoints:
        context_block += f"\n- Hematology parameters: {', '.join(ctx.hematology_endpoints)}"
    if ctx.has_hormones and ctx.hormone_endpoints:
        context_block += f"\n- Hormone parameters: {', '.join(ctx.hormone_endpoints)}"
    if ctx.has_gene_expression and ctx.ge_organs:
        context_block += f"\n- Transcriptomics organs: {', '.join(ctx.ge_organs)}"
    if ctx.has_tissue_conc:
        context_block += "\n- Internal dose assessment: tissue concentration data available"

    # BMDExpress metadata
    if ctx.bmdexpress_version:
        context_block += f"\n- BMDExpress version: {ctx.bmdexpress_version}"
    if ctx.bmds_version:
        context_block += f"\n- BMDS version: {ctx.bmds_version}"
    if ctx.models_fit:
        context_block += f"\n- BMD models fit: {', '.join(ctx.models_fit)}"
    if ctx.bmr_type:
        context_block += f"\n- BMR type: {ctx.bmr_type}"
    if ctx.bmr_factor is not None:
        context_block += f"\n- BMR factor: {ctx.bmr_factor}"
    if ctx.prefilter_method:
        context_block += f"\n- Pre-filter method: {ctx.prefilter_method}"
    if ctx.prefilter_pvalue is not None:
        context_block += f"\n- Pre-filter p-value cutoff: {ctx.prefilter_pvalue}"
    if ctx.constant_variance is not None:
        context_block += f"\n- Constant variance: {'yes' if ctx.constant_variance else 'no'}"

    # Build subsection requirements
    skeleton = build_subsection_skeleton(ctx)
    subsection_keys = [key for key, _, _ in skeleton]

    # Per-subsection guidance for the LLM
    guidelines = _build_subsection_guidelines(ctx, skeleton)

    user_prompt = f"""Generate the Materials and Methods section for a {ctx.duration_days}-day genomic dose-response study report.

{context_block}

## Required Subsections
Generate content for ONLY the following subsections (in order).
Return your response as a JSON object where each key is a subsection identifier
and the value is a string containing 1-3 paragraphs of prose.

Keys to generate: {subsection_keys}

{guidelines}

## Important formatting notes:
- Do NOT include section headers in the text — they will be added by the template.
- Write in past tense, third person, formal NIEHS/NTP technical report style.
- Reference exact study parameters from the context above (dose groups, species, etc.).
- Each value should be a single string. Use \\n\\n to separate multiple paragraphs within a subsection.
- Return ONLY the JSON object, no markdown code fences."""

    return system, user_prompt


def _build_subsection_guidelines(
    ctx: MethodsContext,
    skeleton: list[tuple[str, str, int]],
) -> str:
    """
    Build per-subsection prose guidelines for the LLM prompt.

    Each guideline tells the LLM exactly what to cover in that subsection
    and references the actual study parameters from the context.

    Args:
        ctx:      MethodsContext with study parameters.
        skeleton: The filtered subsection skeleton.

    Returns:
        Formatted string of guidelines.
    """
    dose_str = ", ".join(str(d) for d in ctx.dose_groups) if ctx.dose_groups else "not specified"
    sexes_str = " and ".join(ctx.sexes) if ctx.sexes else "male and female"

    guides: dict[str, str] = {
        "study_design": (
            f"One paragraph covering: animal source and quarantine (7 days), "
            f"randomization by body weight, dose groups ({dose_str} {ctx.dose_unit}), "
            f"dosing schedule ({ctx.duration_days} consecutive days by oral {ctx.route}), "
            f"sample sizes ({ctx.n_per_group} {sexes_str} per treatment group, "
            f"{ctx.n_control} {sexes_str} vehicle control), "
            f"{'biosampling animals for internal dose assessment, ' if ctx.n_biosampling > 0 else ''}"
            f"necropsy timing (approximately 24 hours after the final dose)."
        ),
        "dose_selection": (
            "One paragraph. Reference LD50 predictions if available, "
            "explain the dose spacing rationale (half-log dose spacing), "
            "rationale for top dose selection, and target of no overt systemic toxicity."
        ),
        "chemistry": (
            f"First paragraph: {ctx.chemical_name} source (typically synthesized by contract lab or obtained from commercial supplier), "
            f"lot number (state that lot details are in the full study protocol), "
            f"identity confirmation methods (IR, NMR, or mass spectrometry), purity (typically >95%%), storage conditions. "
            f"Second paragraph: dose formulation preparation in {ctx.vehicle}, "
            f"concentration verification by analytical chemistry, formulation QC analysis."
        ),
        "clinical_exams": (
            "Brief introductory paragraph describing the scope of clinical examinations "
            "performed during the study: clinical observations, body/organ weight collection, "
            "clinical pathology sampling, and (if applicable) tissue collection for internal dose assessment."
        ),
        "clinical_obs": (
            "One paragraph. Standard boilerplate: animals were observed twice daily for morbidity/mortality, "
            "clinical observations were recorded once daily, "
            "cage-side observations included assessment of general appearance, behavior, and respiratory patterns."
        ),
        "body_organ_weights": (
            f"One paragraph. Body weights recorded on study day 0 and at necropsy. "
            f"{'Organ weights: ' + ', '.join(ctx.organ_weight_endpoints[:10]) + '.' if ctx.organ_weight_endpoints else 'Organs were weighed at necropsy.'} "
            f"Absolute and relative (organ-to-body-weight ratio) weights calculated."
        ),
        "clinical_pathology": (
            f"One paragraph covering blood collection method (retroorbital or cardiac puncture under anesthesia), "
            f"sample processing. "
            f"{'Clinical chemistry parameters: ' + ', '.join(ctx.clin_chem_endpoints[:10]) + '. ' if ctx.clin_chem_endpoints else ''}"
            f"{'Hematology parameters: ' + ', '.join(ctx.hematology_endpoints[:10]) + '. ' if ctx.hematology_endpoints else ''}"
            f"{'Hormone parameters: ' + ', '.join(ctx.hormone_endpoints[:5]) + '. ' if ctx.hormone_endpoints else ''}"
            f"Reference the analyzer instruments (e.g., Advia 120 for hematology, AU680 for clinical chemistry)."
        ),
        "internal_dose": (
            "One paragraph. Describe tissue collection for internal dose assessment: "
            "blood/serum and tissue samples collected at necropsy, stored at -80°C, "
            "analyzed by LC-MS/MS for parent compound and/or metabolite concentrations."
        ),
        "transcriptomics": (
            f"Brief introductory paragraph: transcriptomic profiling was performed on "
            f"{', '.join(ctx.ge_organs) if ctx.ge_organs else 'target organs'} "
            f"using the TempO-Seq targeted RNA sequencing platform (BioSpyder Technologies)."
        ),
        "txomics_sample": (
            "One paragraph. RNA was isolated from flash-frozen tissue samples. "
            "Describe tissue homogenization, RNA extraction method (e.g., RNeasy), "
            "RNA quality assessment (RIN values)."
        ),
        "txomics_rna": (
            "One paragraph. TempO-Seq S1500+ platform (BioSpyder Technologies), "
            "library preparation with detector oligos, ligation, amplification, "
            "multiplexed sequencing on Illumina platform."
        ),
        "txomics_seq_processing": (
            "One paragraph. Demultiplexing, alignment to probe reference sequences, "
            "count table generation using the TempO-SeqR pipeline."
        ),
        "txomics_qc": (
            "One paragraph. Outlier detection by principal component analysis and "
            "total read count thresholds. Samples below quality thresholds were excluded "
            "from downstream analysis."
        ),
        "txomics_normalization": (
            "One paragraph. DESeq2 median-of-ratios normalization or TMM normalization. "
            "Describe the normalization method used for count data."
        ),
        "data_analysis": (
            "Brief introductory paragraph: overview of the statistical and dose-response "
            "modeling approaches applied to both apical and transcriptomic endpoints."
        ),
        "stat_analysis": (
            "One paragraph. Standard NIEHS statistical pipeline: "
            "Jonckheere trend test for monotonic dose-response, followed by "
            "Williams test (if monotonic) or Dunnett test (if non-monotonic) for pairwise comparisons. "
            "Shirley nonparametric test used when data did not meet normality/homogeneity assumptions. "
            "Dunn test for non-parametric pairwise comparisons. "
            "Significance threshold: p < 0.05."
        ),
        "bmd_apical": (
            f"One paragraph. Benchmark dose modeling of apical endpoints using "
            f"{'BMDS ' + ctx.bmds_version if ctx.bmds_version else 'EPA BMDS software'}. "
            f"{'Models fit: ' + ', '.join(ctx.models_fit) + '. ' if ctx.models_fit else ''}"
            f"{'BMR: ' + str(ctx.bmr_factor) + ' ' + (ctx.bmr_type or 'standard deviation') + ' from the control mean. ' if ctx.bmr_factor is not None else ''}"
            f"{'Constant variance assumed. ' if ctx.constant_variance else ''}"
            f"Model selection by lowest AIC or Laplace model averaging."
        ),
        "bmd_genomics": (
            f"One paragraph. Benchmark dose modeling of transcriptomic data using "
            f"{ctx.bmdexpress_version or 'BMDExpress'} with "
            f"{'BMDS ' + ctx.bmds_version if ctx.bmds_version else 'EPA BMDS'}. "
            f"{'Pre-filter: ' + ctx.prefilter_method + ' (p < ' + str(ctx.prefilter_pvalue) + ')' if ctx.prefilter_method and ctx.prefilter_pvalue else ''}"
            f"{'Models fit: ' + ', '.join(ctx.models_fit) + '. ' if ctx.models_fit else ''}"
            f"Describe gene-level BMD derivation, GO term / pathway enrichment using "
            f"category analysis, and filtering criteria (goodness-of-fit p > 0.1, "
            f"BMDU/BMDL ratio ≤ 40, minimum 5%% gene set coverage)."
        ),
        "efdr": (
            "One paragraph. Empirical false discovery rate estimation by permutation: "
            "dose labels are randomly shuffled to create null datasets, "
            "the full BMD analysis pipeline is run on permuted data, "
            "and the fraction of false positives at each BMD threshold is estimated. "
            "Reference the number of permutations used."
        ),
        "data_accessibility": (
            "One paragraph. Data availability statement: "
            "all raw and processed data are available through the NIEHS Chemical Effects "
            "in Biological Systems (CEBS) database or the study's data repository. "
            "Provide placeholder for DOI or accession number."
        ),
    }

    lines = ["## Guidelines per subsection:"]
    for key, heading, level in skeleton:
        if key in guides:
            lines.append(f"- {key}: {guides[key]}")

    return "\n".join(lines)


