"""rendering.bookshelf_preview — render a BITS <book> into a visually faithful
NCBI-Bookshelf-style HTML preview.

This transforms the EXACT artifact we submit (the BITS book emitted by
`jats_generator.generate_bits`) into an HTML page styled to look like the reader
view of a book on NCBI Bookshelf: a left table-of-contents rail and a single
scrolling content column with Bookshelf-like typography, tables and cross-refs.

It is a LOOKALIKE, deliberately scoped to the CONTENT column only.  It does NOT
reproduce NCBI's site chrome (masthead, portlets, analytics) or NCBI/NIEHS
branding — that markup is generated by NCBI's portal framework from their own
(unpublished) production XSLT, and reproducing it would be impersonation.  The
built-in CSS here is calibrated by eye against the published reader view, so the
result is authoritative for structure/content and approximate for exact
appearance.  It is a preview of the ultimate deliverable, never a substitute for
NCBI's own QA render.

Real-CSS override (see assets/bookshelf/README): if a vendored stylesheet exists
at ``assets/bookshelf/bookshelf.css`` it is inlined INSTEAD of the built-in CSS,
so a copy of NCBI's actual book stylesheet (grabbed on a host that isn't
bot-blocked) tightens the fidelity with no code change.

Public API:
    render_book_xml(xml, base_dir=None) -> str   # from an XML string/bytes
    render_book_file(xml_path) -> str            # from a file on disk
"""

from __future__ import annotations

import html
from pathlib import Path

from lxml import etree

XLINK = "http://www.w3.org/1999/xlink"

# Optional vendored real Bookshelf stylesheet; overrides the built-in CSS.
_REPO = Path(__file__).resolve().parents[1]
_VENDORED_CSS = _REPO / "assets" / "bookshelf" / "bookshelf.css"

# Block-level BITS elements we render inside a body/section (anything else at the
# block level — book-part-meta, title — is handled by the caller or ignored).
_BLOCK_TAGS = frozenset({"sec", "p", "table-wrap", "fig", "list", "boxed-text"})


def _ln(el) -> str:
    """Local name of an element tag (namespace-stripped)."""
    return etree.QName(el).localname if isinstance(el.tag, str) else ""


def _esc(s: str | None) -> str:
    return html.escape(s or "", quote=True)


# ---------------------------------------------------------------------------
# Inline runs (text + <ext-link>/<xref>/<italic>/<bold>/<sub>/<sup>)
# ---------------------------------------------------------------------------

def _inline(el) -> str:
    """Serialize an element's mixed inline content to HTML, preserving tails."""
    parts: list[str] = []
    if el.text:
        parts.append(_esc(el.text))
    for child in el:
        parts.append(_inline_child(child))
        if child.tail:
            parts.append(_esc(child.tail))
    return "".join(parts)


def _inline_child(child) -> str:
    tag = _ln(child)
    inner = _inline(child)
    if tag == "ext-link":
        href = child.get(f"{{{XLINK}}}href") or child.get("href") or ""
        return (f'<a href="{_esc(href)}" target="_blank" rel="noopener">'
                f'{inner or _esc(href)}</a>')
    if tag == "xref":
        rid = child.get("rid", "")
        return f'<a class="xref" href="#{_esc(rid)}">{inner}</a>'
    if tag in ("italic", "i"):
        return f"<em>{inner}</em>"
    if tag in ("bold", "b"):
        return f"<strong>{inner}</strong>"
    if tag == "sub":
        return f"<sub>{inner}</sub>"
    if tag == "sup":
        return f"<sup>{inner}</sup>"
    if tag == "monospace":
        return f"<code>{inner}</code>"
    # Unknown inline element: keep its text content, drop the wrapper.
    return inner


def _title_text(el) -> str:
    """Plain-text title of a sec/part (for the TOC), from its <title> child."""
    t = el.find("title")
    return "".join(t.itertext()).strip() if t is not None else ""


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------

def _render_table(table_el) -> str:
    groups: list[str] = []
    for section in table_el:
        stag = _ln(section)
        if stag not in ("thead", "tbody", "tfoot"):
            continue
        rows: list[str] = []
        for tr in section:
            if _ln(tr) != "tr":
                continue
            cells: list[str] = []
            for cell in tr:
                ctag = _ln(cell)
                if ctag not in ("th", "td"):
                    continue
                span = cell.get("colspan")
                attrs = f' colspan="{_esc(span)}"' if span else ""
                # A spanning td is a group/sex sub-header row in our tables.
                cls = ' class="grouprow"' if (ctag == "td" and span) else ""
                cells.append(f"<{ctag}{attrs}{cls}>{_inline(cell)}</{ctag}>")
            rows.append("<tr>" + "".join(cells) + "</tr>")
        groups.append(f"<{stag}>" + "".join(rows) + f"</{stag}>")
    return ('<div class="table-scroll"><table class="bk-table">'
            + "".join(groups) + "</table></div>")


def _render_table_wrap(el) -> str:
    tid = el.get("id", "")
    label = el.findtext("label")
    cap = el.find("caption")
    caption_html = _inline(cap.find("p")) if (cap is not None and cap.find("p") is not None) else \
        (_inline(cap) if cap is not None else "")
    head = ""
    if label or caption_html:
        lab = f'<span class="table-label">{_esc(label)}.</span> ' if label else ""
        head = f'<div class="table-caption">{lab}{caption_html}</div>'
    table = el.find("table")
    table_html = _render_table(table) if table is not None else ""
    foot = ""
    twf = el.find("table-wrap-foot")
    if twf is not None:
        notes = ["".join(f"<div class=\"fn\">{_inline(p)}</div>"
                         for p in fn.findall("p"))
                 for fn in twf.findall("fn")]
        notes += [f'<div class="fn">{_inline(p)}</div>' for p in twf.findall("p")]
        if notes:
            foot = f'<div class="table-foot">{"".join(notes)}</div>'
    anchor = f' id="{_esc(tid)}"' if tid else ""
    return f'<div class="table-wrap"{anchor}>{head}{table_html}{foot}</div>'


def _render_fig(el, base_dir: Path | None, images: dict | None) -> str:
    fid = el.get("id", "")
    label = el.findtext("label")
    cap = el.find("caption")
    caption_html = _inline(cap.find("p")) if (cap is not None and cap.find("p") is not None) else \
        (_inline(cap) if cap is not None else "")
    graphic = el.find("graphic")
    href = ""
    if graphic is not None:
        href = graphic.get(f"{{{XLINK}}}href") or graphic.get("href") or ""
    # An `images` map (filename → base64 PNG, supplied by the caller from the
    # session data) makes the preview self-contained: the BITS <graphic> only
    # references a filename, so the bytes are inlined here as a data URI.  Falls
    # back to a real file next to the page, then a visible placeholder.
    b64 = (images or {}).get(href)
    if b64:
        src = b64 if b64.startswith("data:") else f"data:image/png;base64,{b64}"
        img = f'<img src="{src}" alt="{_esc(caption_html)}">'
    elif href and base_dir is not None and (base_dir / href).exists():
        img = f'<img src="{_esc(href)}" alt="{_esc(caption_html)}">'
    else:
        img = f'<div class="fig-missing">[figure: {_esc(href or "image not bundled")}]</div>'
    lab = f'<span class="fig-label">{_esc(label)}.</span> ' if label else ""
    anchor = f' id="{_esc(fid)}"' if fid else ""
    return (f'<figure class="fig"{anchor}>{img}'
            f'<figcaption>{lab}{caption_html}</figcaption></figure>')


# ---------------------------------------------------------------------------
# Section / body walk
# ---------------------------------------------------------------------------

def _render_blocks(children, level: int, out: list[str], base_dir: Path | None,
                   images: dict | None) -> None:
    for el in children:
        tag = _ln(el)
        if tag == "sec":
            _render_sec(el, level, out, base_dir, images)
        elif tag == "p":
            out.append(f"<p>{_inline(el)}</p>")
        elif tag == "table-wrap":
            out.append(_render_table_wrap(el))
        elif tag == "fig":
            out.append(_render_fig(el, base_dir, images))
        elif tag == "list":
            items = "".join(f"<li>{_inline(li)}</li>"
                            for li in el.findall("list-item"))
            out.append(f'<ul class="bk-list">{items}</ul>')
        elif tag == "boxed-text":
            inner: list[str] = []
            _render_blocks(list(el), level, inner, base_dir, images)
            out.append(f'<div class="boxed">{"".join(inner)}</div>')
        # book-part-meta, title, etc. handled by the caller / ignored here.


def _render_sec(sec_el, level: int, out: list[str], base_dir: Path | None,
                images: dict | None) -> None:
    hl = min(level, 6)
    sid = sec_el.get("id", "")
    title = sec_el.find("title")
    anchor = f' id="{_esc(sid)}"' if sid else ""
    if title is not None:
        out.append(f'<h{hl}{anchor}>{_inline(title)}</h{hl}>')
    elif anchor:
        out.append(f'<span{anchor}></span>')
    kids = [c for c in sec_el if _ln(c) != "title"]
    _render_blocks(kids, level + 1, out, base_dir, images)


def _effective_children(body_el, part_title: str):
    """The blocks to render for a chapter/part body.  A body that is a single
    <sec> repeating the part title (Background → sec-background) is UNWRAPPED so
    the title is not printed twice; its own children become the part's blocks."""
    kids = [c for c in body_el if _ln(c) in _BLOCK_TAGS]
    if (len(kids) == 1 and _ln(kids[0]) == "sec"
            and _title_text(kids[0]).lower() == (part_title or "").lower()):
        return [c for c in kids[0] if _ln(c) != "title"]
    return kids


# ---------------------------------------------------------------------------
# Whole-book assembly
# ---------------------------------------------------------------------------

def _meta(root) -> dict:
    bm = root.find("book-meta")

    def get(p):
        return bm.findtext(p) if bm is not None else None

    return {
        "title": get("book-title-group/book-title") or "Untitled",
        "publisher": get("publisher/publisher-name") or "",
        "loc": get("publisher/publisher-loc") or "",
        "issn": get("issn") or "",
        "year": get("pub-date/year") or "",
        "abstract": bm.find("abstract") if bm is not None else None,
    }


def _render_part(part_el, base_dir, nav: list[tuple], images: dict | None,
                 *, is_chapter: bool):
    """Render one front-matter part or one body chapter; append its top-level
    sections to `nav`. Returns the section HTML."""
    pid = part_el.get("id", "")
    tg = part_el.find("book-part-meta/title-group/title")
    direct = part_el.find("title")
    title_el = tg if tg is not None else direct
    title = "".join(title_el.itertext()).strip() if title_el is not None else ""
    body = part_el.find("body")
    if body is None:
        body = part_el.find("named-book-part-body")
    out: list[str] = [f'<h2 id="{_esc(pid)}" class="part-title">{_esc(title)}</h2>']
    nav.append((pid, title, 1))
    if body is not None:
        children = _effective_children(body, title) if is_chapter else \
            [c for c in body if _ln(c) in _BLOCK_TAGS]
        for c in children:
            if _ln(c) == "sec" and c.get("id"):
                nav.append((c.get("id"), _title_text(c), 2))
        _render_blocks(children, 3, out, base_dir, images)
    else:
        _render_blocks([c for c in part_el if _ln(c) in _BLOCK_TAGS], 3, out, base_dir, images)
    return f'<section class="chapter">{"".join(out)}</section>'


def _render_ref_list(rl, nav: list[tuple]) -> str:
    """A BITS <ref-list> → a numbered References section (each <ref> is a
    <mixed-citation> line)."""
    rid = rl.get("id", "ref-list1")
    title_el = rl.find("title")
    title = _inline(title_el) if title_el is not None else "References"
    nav.append((rid, "".join(rl.find("title").itertext()).strip() if title_el is not None else "References", 1))
    items: list[str] = []
    for ref in rl.findall("ref"):
        mc = ref.find("mixed-citation")
        text = _inline(mc) if mc is not None else _esc("".join(ref.itertext()).strip())
        items.append(f"<li>{text}</li>")
    body = f'<ol class="ref-list">{"".join(items)}</ol>' if items else ""
    return (f'<section class="chapter"><h2 id="{_esc(rid)}" class="part-title">{title}</h2>'
            f'{body}</section>')


def _render_abstract(abs_el, base_dir, nav: list[tuple]) -> str:
    nav.append(("abstract", "Abstract", 1))
    parts = ['<section class="chapter"><h2 id="abstract" class="part-title">Abstract</h2>']
    for sec in abs_el.findall("sec"):
        label = _title_text(sec)
        for p in sec.findall("p"):
            run_in = f'<span class="abs-label">{_esc(label)}.</span> ' if label else ""
            parts.append(f'<p class="abstract-p">{run_in}{_inline(p)}</p>')
            label = ""  # only the first paragraph of a sec gets the run-in label
    parts.append("</section>")
    return "".join(parts)


def _download_rail(downloads: list[dict] | None) -> str:
    """The right-rail "Download" panel (Bookshelf's right sidebar analogue) from a
    list of {label, href} links.  Empty string when there are none, so the preview
    surface / CLI (which pass no downloads) render with just the TOC + content."""
    if not downloads:
        return ""
    links = "".join(
        f'<li><a href="{_esc(d["href"])}">{_esc(d["label"])}</a></li>'
        for d in downloads if d.get("href") and d.get("label")
    )
    if not links:
        return ""
    return (
        '<aside class="side-rail">'
        '<div class="rail-panel"><div class="rail-title">Download</div>'
        f'<ul class="rail-links">{links}</ul></div>'
        '</aside>'
    )


def _build_html(root, base_dir, images: dict | None, downloads: list[dict] | None) -> str:
    m = _meta(root)
    nav: list[tuple] = []
    body_html: list[str] = []

    if m["abstract"] is not None:
        body_html.append(_render_abstract(m["abstract"], base_dir, nav))

    fm = root.find("front-matter")
    if fm is not None:
        for part in fm:
            if _ln(part) in ("foreword", "front-matter-part", "ack", "dedication",
                             "preface", "book-part"):
                body_html.append(_render_part(part, base_dir, nav, images, is_chapter=False))

    bb = root.find("book-body")
    if bb is not None:
        for part in bb.findall("book-part"):
            body_html.append(_render_part(part, base_dir, nav, images, is_chapter=True))

    back = root.find("book-back")
    if back is not None:
        for part in back:
            tag = _ln(part)
            if tag in ("book-app-group", "app-group"):
                for app in part:
                    if _ln(app) in ("book-app", "app"):
                        body_html.append(_render_part(app, base_dir, nav, images, is_chapter=True))
            elif tag in ("book-app", "app"):
                body_html.append(_render_part(part, base_dir, nav, images, is_chapter=True))
            elif tag == "ref-list":
                body_html.append(_render_ref_list(part, nav))
            elif tag in ("ack", "glossary", "book-part"):
                body_html.append(_render_part(part, base_dir, nav, images, is_chapter=True))

    nav_html = ['<div class="toc-title">Contents</div><ul class="toc">']
    for tid, ttl, lvl in nav:
        nav_html.append(
            f'<li class="toc-l{lvl}"><a href="#{_esc(tid)}">{_esc(ttl)}</a></li>')
    nav_html.append("</ul>")

    bits = [x for x in (m["publisher"], m["loc"], m["year"]) if x]
    if m["issn"]:
        bits.append(f"ISSN {m['issn']}")
    subtitle = " · ".join(bits)
    return _PAGE.format(
        title=_esc(m["title"]),
        subtitle=_esc(subtitle),
        nav="".join(nav_html),
        body="".join(body_html),
        side_rail=_download_rail(downloads),
        css=_stylesheet(),
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def _parse(xml) -> etree._Element:
    parser = etree.XMLParser(load_dtd=False, no_network=True,
                             resolve_entities=False, recover=True)
    if isinstance(xml, str):
        xml = xml.encode("utf-8")
    return etree.fromstring(xml, parser)


def render_book_xml(xml, base_dir: Path | None = None,
                    images: dict | None = None,
                    downloads: list[dict] | None = None) -> str:
    """Render a BITS <book> (XML string or bytes) to a Bookshelf-style HTML page.

    `base_dir` roots relative figure `graphic` hrefs (a missing/absent image
    renders a visible placeholder rather than a broken link).  `images` is an
    optional {filename → base64-PNG} map that inlines figure images as data URIs
    so the page is self-contained — use chart_images(data) to build it from the
    session data (the BITS XML only carries the filename, not the bytes).
    `downloads` is an optional list of {label, href} rendered as a right-rail
    "Download" panel (the /Bookshelf page passes the PDF + DOCX links); omitted,
    the page shows just the TOC + content (the in-app preview surface / CLI).
    """
    return _build_html(_parse(xml), base_dir, images, downloads)


def render_book_file(xml_path: Path) -> str:
    """Render a BITS <book> XML file to a Bookshelf-style HTML page."""
    xml_path = Path(xml_path)
    return render_book_xml(xml_path.read_bytes(),
                           base_dir=xml_path.resolve().parent)


def chart_images(data: dict) -> dict[str, str]:
    """Build the {filename → base64-PNG} map render_book_xml inlines, from a
    marshalled report `data` dict: every genomics chart carries its own
    `filename` + `png_b64` (genomics_charts.attach_genomics_charts).  Empty when
    the report has no charts (e.g. the shipped template ships `charts: []`)."""
    out: dict[str, str] = {}
    for entry in data.get("genomics_sections") or []:
        for chart in entry.get("charts") or []:
            fn, b64 = chart.get("filename"), chart.get("png_b64")
            if fn and b64:
                out[fn] = b64
    return out


def _stylesheet() -> str:
    """The inlined stylesheet: the vendored real Bookshelf CSS when present
    (assets/bookshelf/bookshelf.css), else the built-in eye-calibrated CSS."""
    try:
        if _VENDORED_CSS.exists():
            return _VENDORED_CSS.read_text(encoding="utf-8")
    except OSError:
        pass
    return _CSS


# ---------------------------------------------------------------------------
# Page shell + built-in CSS (Bookshelf reader-view lookalike; calibrated by eye)
# ---------------------------------------------------------------------------

_CSS = """
:root{
  --ink:#1a1a1a; --muted:#5c6670; --rule:#d5dbe0; --link:#205493;
  --accent:#2e6db4; --bg:#ffffff; --nav-bg:#f5f7f9; --grouprow:#eef2f5;
  --thead:#eef2f5; --banner:#fff8e1; --banner-br:#e6d48a;
}
*{box-sizing:border-box;}
html,body{margin:0;padding:0;}
body{
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
  color:var(--ink); background:var(--bg); line-height:1.55; font-size:16px;
  -webkit-font-smoothing:antialiased;
}
a{color:var(--link); text-decoration:none;}
a:hover{text-decoration:underline;}
.preview-banner{
  background:var(--banner); border-bottom:1px solid var(--banner-br);
  color:#5b4a00; font-size:12.5px; padding:7px 18px; text-align:center;
}
.masthead{border-bottom:1px solid var(--rule); padding:18px 18px 14px;}
.masthead .booktitle{font-size:1.15rem; font-weight:700; color:#12263a;}
.masthead .booksub{font-size:.8rem; color:var(--muted); margin-top:3px;}
.layout{display:flex; align-items:flex-start; max-width:1180px; margin:0 auto;}
nav.toc-rail{
  flex:0 0 258px; position:sticky; top:0; align-self:flex-start;
  max-height:100vh; overflow:auto; background:var(--nav-bg);
  border-right:1px solid var(--rule); padding:20px 14px 40px;
}
.toc-title{font-size:.72rem; font-weight:700; letter-spacing:.08em;
  text-transform:uppercase; color:var(--muted); margin:0 0 10px 6px;}
ul.toc{list-style:none; margin:0; padding:0; font-size:.86rem;}
ul.toc li{margin:1px 0;}
ul.toc a{display:block; padding:3px 8px; border-radius:4px; color:#26424f;}
ul.toc a:hover{background:#e4eaee; text-decoration:none;}
.toc-l1 a{font-weight:600;}
.toc-l2 a{padding-left:22px; color:#4a5a63; font-size:.83rem;}
main{flex:1 1 auto; min-width:0; padding:26px 46px 90px; max-width:820px;}
section.chapter{margin:0 0 34px; padding-bottom:8px;}
h2.part-title{
  font-size:1.62rem; font-weight:700; color:#12263a; line-height:1.2;
  margin:34px 0 14px; padding-bottom:8px; border-bottom:2px solid #e2e7eb;
}
section.chapter:first-child h2.part-title{margin-top:6px;}
h3{font-size:1.22rem; font-weight:700; color:#1b3a4b; margin:26px 0 8px;}
h4{font-size:1.04rem; font-weight:700; color:#2a2a2a; margin:20px 0 6px;}
h5,h6{font-size:.98rem; font-weight:700; color:#2a2a2a; margin:16px 0 6px;}
p{margin:0 0 12px;}
.abstract-p{margin-bottom:10px;}
.abs-label{font-weight:700;}
sup{font-size:.72em;} sub{font-size:.72em;}
.xref{white-space:nowrap;}
.table-wrap{margin:20px 0 24px; font-size:.92rem;}
.table-caption{font-weight:400; margin:0 0 8px; line-height:1.4;}
.table-label{font-weight:700;}
.table-scroll{overflow-x:auto; border:1px solid var(--rule);}
table.bk-table{border-collapse:collapse; width:100%; font-size:.8rem; background:#fff;}
table.bk-table th, table.bk-table td{
  border:0; border-bottom:1px solid #e3e8ec; padding:5px 9px;
  text-align:right; vertical-align:top; white-space:nowrap;}
table.bk-table thead th{
  background:var(--thead); border-bottom:2px solid #c7d0d7; font-weight:700;
  text-align:right; color:#22333f; position:sticky; top:0;}
table.bk-table td:first-child, table.bk-table th:first-child{text-align:left;}
table.bk-table tr td.grouprow{
  background:var(--grouprow); font-weight:700; text-align:left;
  color:#22333f; border-bottom:1px solid #c7d0d7;}
.table-foot{margin:8px 0 0; font-size:.78rem; color:var(--muted); line-height:1.45;}
.table-foot .fn{margin:2px 0;}
.fig{margin:22px 0; text-align:center;}
.fig img{max-width:100%; height:auto; border:1px solid var(--rule);}
.fig .fig-missing{color:var(--muted); font-style:italic; padding:26px;
  border:1px dashed var(--rule); background:#fafbfc;}
.fig figcaption{font-size:.86rem; color:#333; margin-top:8px; text-align:left;}
.fig-label,.fig figcaption .fig-label{font-weight:700;}
.boxed{border:1px solid var(--rule); background:#fafbfc; padding:12px 16px;
  margin:16px 0; border-radius:4px;}
ul.bk-list{margin:0 0 12px 22px;}
ol.ref-list{font-size:.9rem; line-height:1.5; padding-left:26px;}
ol.ref-list li{margin:0 0 8px;}
.docfoot{border-top:1px solid var(--rule); color:var(--muted); font-size:12px;
  padding:16px 46px 40px; max-width:1180px; margin:0 auto;}
/* Right rail — the Bookshelf "Views"/download sidebar. */
aside.side-rail{flex:0 0 220px; align-self:flex-start; position:sticky; top:0;
  max-height:100vh; overflow:auto; padding:22px 16px 40px;}
.rail-panel{border:1px solid var(--rule); border-radius:6px; overflow:hidden; background:#fff;}
.rail-title{background:var(--nav-bg); border-bottom:1px solid var(--rule);
  font-size:.72rem; font-weight:700; letter-spacing:.08em; text-transform:uppercase;
  color:var(--muted); padding:8px 12px;}
ul.rail-links{list-style:none; margin:0; padding:6px 0;}
ul.rail-links li{margin:0;}
ul.rail-links a{display:block; padding:8px 14px; color:var(--link); font-size:.9rem;}
ul.rail-links a:hover{background:#eef2f5; text-decoration:none;}
@media (max-width:900px){
  .layout{flex-direction:column;}
  nav.toc-rail{position:static; flex-basis:auto; max-height:none; width:100%;
    border-right:0; border-bottom:1px solid var(--rule);}
  aside.side-rail{position:static; flex-basis:auto; max-height:none; width:100%;
    border-top:1px solid var(--rule); order:3;}
  main{padding:20px 18px 60px;}
}
"""

_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Bookshelf preview</title>
<style>{css}</style>
</head>
<body>
<div class="preview-banner">Bookshelf-style preview — generated by rlm-bmdx from the report's BITS XML. Not an NCBI/NIEHS page; approximate appearance only.</div>
<header class="masthead">
  <div class="booktitle">{title}</div>
  <div class="booksub">{subtitle}</div>
</header>
<div class="layout">
  <nav class="toc-rail">{nav}</nav>
  <main>{body}</main>
  {side_rail}
</div>
<div class="docfoot">Rendered from BITS/JATS &lt;book&gt; via rendering/bookshelf_preview.py — a content-only lookalike of the NCBI Bookshelf reader view.</div>
</body>
</html>
"""
