"""rendering.bookshelf_preview — render a BITS <book> into a visually faithful
NCBI-Bookshelf-style HTML preview, page by page.

This transforms the EXACT artifact we submit (the BITS book emitted by
`jats_generator.generate_bits`) into an HTML page styled and *navigated* like the
reader view of a book on NCBI Bookshelf: a **Contents landing** plus **one page
per top-level section**, with ``< Prev`` / ``Next >`` pagination, a "Contents"
link, and a right-hand rail of "Views" (downloads) + a section navigator.  The
whole book is emitted into ONE self-contained HTML document; navigation between
"pages" is client-side (hash-routed, ``#<section-id>``), so the module's public
API still returns a single string that the CLI, the preview surface and saved
``output/*.html`` all consume unchanged.  Cross-references (``xref``) across
pages work: a click switches to the target's page and scrolls to it.

The content column mirrors the real Bookshelf reader DOM (``main-content
lit-style`` › ``meta-content fm-sec`` h1 with ``label``/``title`` spans ›
``body-content whole_rhythm`` with ``table``/``large_tbl`` and ``figure bk_fig``
blocks, ``temp-labeled-list`` footnotes, ``pagination``/``page_link``).  Matching
those class names means a copy of NCBI's real ``books.min.css`` dropped at
``assets/bookshelf/bookshelf.css`` styles the content faithfully with no code
change (see ``_stylesheet``).

It is a LOOKALIKE, deliberately scoped to the reader CONTENT.  It does NOT
reproduce NCBI's site chrome — the U.S.-government banner, the NIH/NLM/NCBI
logos and universal header, the portlets or the NCBI footer.  That markup is
generated by NCBI's portal framework from their own (unpublished) production
XSLT, and reproducing it would be impersonation.  A prominent banner marks every
page as a preview, not an NCBI/NIEHS page.  It is a preview of the ultimate
deliverable, never a substitute for NCBI's own QA render.

Public API:
    render_book_xml(xml, base_dir=None, images=None, downloads=None) -> str
    render_book_file(xml_path) -> str
    chart_images(data) -> {filename: base64_png}
"""

from __future__ import annotations

import html
import json
import string
from dataclasses import dataclass, field
from pathlib import Path

from lxml import etree

XLINK = "http://www.w3.org/1999/xlink"

# Optional vendored real Bookshelf stylesheet; overrides the built-in CSS.
_REPO = Path(__file__).resolve().parents[1]
_VENDORED_CSS = _REPO / "assets" / "bookshelf" / "bookshelf.css"

# Block-level BITS elements we render inside a body/section (anything else at the
# block level — book-part-meta, title — is handled by the caller or ignored).
_BLOCK_TAGS = frozenset({"sec", "p", "table-wrap", "fig", "list", "boxed-text"})


def _ln(el) -> str:
    """Local name of an element tag (namespace-stripped)."""
    return etree.QName(el).localname if isinstance(el.tag, str) else ""


def _esc(s: str | None) -> str:
    return html.escape(s or "", quote=True)


# ---------------------------------------------------------------------------
# Inline runs (text + <ext-link>/<xref>/<italic>/<bold>/<sub>/<sup>)
# ---------------------------------------------------------------------------

def _inline(el) -> str:
    """Serialize an element's mixed inline content to HTML, preserving tails."""
    parts: list[str] = []
    if el.text:
        parts.append(_esc(el.text))
    for child in el:
        parts.append(_inline_child(child))
        if child.tail:
            parts.append(_esc(child.tail))
    return "".join(parts)


def _inline_child(child) -> str:
    tag = _ln(child)
    inner = _inline(child)
    if tag == "ext-link":
        href = child.get(f"{{{XLINK}}}href") or child.get("href") or ""
        return (f'<a href="{_esc(href)}" target="_blank" rel="noopener">'
                f'{inner or _esc(href)}</a>')
    if tag == "xref":
        rid = child.get("rid", "")
        return f'<a class="xref bk_pop" href="#{_esc(rid)}">{inner}</a>'
    if tag in ("italic", "i"):
        return f"<em>{inner}</em>"
    if tag in ("bold", "b"):
        return f"<strong>{inner}</strong>"
    if tag == "sub":
        return f"<sub>{inner}</sub>"
    if tag == "sup":
        return f"<sup>{inner}</sup>"
    if tag == "monospace":
        return f'<code class="bk_tt">{inner}</code>'
    # Unknown inline element: keep its text content, drop the wrapper.
    return inner


def _title_text(el) -> str:
    """Plain-text title of a sec/part (for the TOC), from its <title> child."""
    t = el.find("title")
    return "".join(t.itertext()).strip() if t is not None else ""


# ---------------------------------------------------------------------------
# Tables — real Bookshelf DOM: div.table › h3(label+title) › div.large_tbl ›
# table.no_margin, with temp-labeled-list footnotes.
# ---------------------------------------------------------------------------

def _render_table(table_el) -> str:
    groups: list[str] = []
    for section in table_el:
        stag = _ln(section)
        if stag not in ("thead", "tbody", "tfoot"):
            continue
        rows: list[str] = []
        for tr in section:
            if _ln(tr) != "tr":
                continue
            cells: list[str] = []
            for cell in tr:
                ctag = _ln(cell)
                if ctag not in ("th", "td"):
                    continue
                span = cell.get("colspan")
                attrs = f' colspan="{_esc(span)}"' if span else ""
                # A spanning td is a group/sex sub-header row in our tables.
                cls = ' class="grouprow"' if (ctag == "td" and span) else ""
                cells.append(f"<{ctag}{attrs}{cls}>{_inline(cell)}</{ctag}>")
            rows.append("<tr>" + "".join(cells) + "</tr>")
        groups.append(f"<{stag}>" + "".join(rows) + f"</{stag}>")
    return '<table class="no_margin">' + "".join(groups) + "</table>"


def _temp_labeled(inner_html: str) -> str:
    """A Bookshelf ``temp-labeled-list`` block — the small footnote/abbreviation
    list rendered under tables and figures."""
    return ('<div><dl class="temp-labeled-list small"><dt></dt><dd><div>'
            f'{inner_html}</div></dd></dl></div>')


def _render_table_wrap(el) -> str:
    tid = el.get("id", "")
    label = el.findtext("label")
    cap = el.find("caption")
    caption_html = _inline(cap.find("p")) if (cap is not None and cap.find("p") is not None) else \
        (_inline(cap) if cap is not None else "")
    head = ""
    if label or caption_html:
        lab = f'<span class="label">{_esc(label)}</span>' if label else ""
        head = f'<h3>{lab}<span class="title">{caption_html}</span></h3>'
    table = el.find("table")
    table_html = _render_table(table) if table is not None else ""
    body = f'<div class="large_tbl">{table_html}</div>'
    foot = ""
    twf = el.find("table-wrap-foot")
    if twf is not None:
        notes = ["".join(f'<p class="no_margin">{_inline(p)}</p>'
                         for p in fn.findall("p"))
                 for fn in twf.findall("fn")]
        notes += [f'<p class="no_margin">{_inline(p)}</p>' for p in twf.findall("p")]
        if notes:
            foot = _temp_labeled("".join(notes))
    anchor = f' id="{_esc(tid)}"' if tid else ""
    return f'<div class="table"{anchor}>{head}{body}{foot}</div>'


def _render_fig(el, base_dir: Path | None, images: dict | None) -> str:
    fid = el.get("id", "")
    label = el.findtext("label")
    cap = el.find("caption")
    caption_html = _inline(cap.find("p")) if (cap is not None and cap.find("p") is not None) else \
        (_inline(cap) if cap is not None else "")
    graphic = el.find("graphic")
    href = ""
    if graphic is not None:
        href = graphic.get(f"{{{XLINK}}}href") or graphic.get("href") or ""
    # An `images` map (filename → base64 PNG, supplied by the caller from the
    # session data) makes the preview self-contained: the BITS <graphic> only
    # references a filename, so the bytes are inlined here as a data URI.  Falls
    # back to a real file next to the page, then a visible placeholder.
    alt = _esc(label or caption_html)
    b64 = (images or {}).get(href)
    if b64:
        src = b64 if b64.startswith("data:") else f"data:image/png;base64,{b64}"
        graphic_html = f'<div class="graphic"><img src="{src}" alt="{alt}"></div>'
    elif href and base_dir is not None and (base_dir / href).exists():
        graphic_html = f'<div class="graphic"><img src="{_esc(href)}" alt="{alt}"></div>'
    else:
        graphic_html = (f'<div class="graphic"><div class="fig-missing">'
                        f'[figure: {_esc(href or "image not bundled")}]</div></div>')
    lab = f'<h3><span class="label">{_esc(label)}</span></h3>' if label else ""
    caption = f'<div class="caption"><p>{caption_html}</p></div>' if caption_html else ""
    anchor = f' id="{_esc(fid)}"' if fid else ""
    return f'<div class="figure bk_fig"{anchor}>{graphic_html}{lab}{caption}</div>'


# ---------------------------------------------------------------------------
# Section / body walk
# ---------------------------------------------------------------------------

def _render_blocks(children, level: int, out: list[str], base_dir: Path | None,
                   images: dict | None) -> None:
    for el in children:
        tag = _ln(el)
        if tag == "sec":
            _render_sec(el, level, out, base_dir, images)
        elif tag == "p":
            out.append(f"<p>{_inline(el)}</p>")
        elif tag == "table-wrap":
            out.append(_render_table_wrap(el))
        elif tag == "fig":
            out.append(_render_fig(el, base_dir, images))
        elif tag == "list":
            items = "".join(f"<li>{_inline(li)}</li>"
                            for li in el.findall("list-item"))
            out.append(f'<ul class="bk-list">{items}</ul>')
        elif tag == "boxed-text":
            inner: list[str] = []
            _render_blocks(list(el), level, inner, base_dir, images)
            out.append(f'<div class="boxed">{"".join(inner)}</div>')
        # book-part-meta, title, etc. handled by the caller / ignored here.


def _render_sec(sec_el, level: int, out: list[str], base_dir: Path | None,
                images: dict | None) -> None:
    hl = min(level, 6)
    sid = sec_el.get("id", "")
    title = sec_el.find("title")
    anchor = f' id="{_esc(sid)}"' if sid else ""
    if title is not None:
        out.append(f'<h{hl}{anchor}>{_inline(title)}</h{hl}>')
    elif anchor:
        out.append(f'<span{anchor}></span>')
    kids = [c for c in sec_el if _ln(c) != "title"]
    _render_blocks(kids, level + 1, out, base_dir, images)


def _effective_children(body_el, part_title: str):
    """The blocks to render for a chapter/part body.  A body that is a single
    <sec> repeating the part title (Background → sec-background) is UNWRAPPED so
    the title is not printed twice; its own children become the part's blocks."""
    kids = [c for c in body_el if _ln(c) in _BLOCK_TAGS]
    if (len(kids) == 1 and _ln(kids[0]) == "sec"
            and _title_text(kids[0]).lower() == (part_title or "").lower()):
        return [c for c in kids[0] if _ln(c) != "title"]
    return kids


# ---------------------------------------------------------------------------
# Book → ordered pages
# ---------------------------------------------------------------------------

@dataclass
class _Page:
    """One reader "page": a top-level section rendered as its own view."""
    slug: str
    kind: str                       # abstract|frontmatter|chapter|appendix|refs
    title: str
    label: str = ""                 # "Appendix D" (appendices) else ""
    body: str = ""                  # inner HTML of .body-content
    subnav: list[tuple[str, str]] = field(default_factory=list)  # (id, title)


def _meta(root) -> dict:
    bm = root.find("book-meta")

    def get(p):
        return bm.findtext(p) if bm is not None else None

    return {
        "title": get("book-title-group/book-title") or "Untitled",
        "publisher": get("publisher/publisher-name") or "",
        "loc": get("publisher/publisher-loc") or "",
        "issn": get("issn") or "",
        "year": get("pub-date/year") or "",
        "abstract": bm.find("abstract") if bm is not None else None,
    }


def _part_page(part_el, base_dir, images, *, kind: str, label: str = "") -> _Page:
    """Render one front-matter part / body chapter / appendix into a _Page."""
    pid = part_el.get("id", "") or f"sec-{kind}"
    tg = part_el.find("book-part-meta/title-group/title")
    direct = part_el.find("title")
    title_el = tg if tg is not None else direct
    title = "".join(title_el.itertext()).strip() if title_el is not None else ""
    body = part_el.find("body")
    if body is None:
        body = part_el.find("named-book-part-body")
    out: list[str] = []
    subnav: list[tuple[str, str]] = []
    is_chapter = kind in ("chapter", "appendix")
    if body is not None:
        children = _effective_children(body, title) if is_chapter else \
            [c for c in body if _ln(c) in _BLOCK_TAGS]
        for c in children:
            if _ln(c) == "sec" and c.get("id"):
                subnav.append((c.get("id"), _title_text(c)))
        _render_blocks(children, 2, out, base_dir, images)
    else:
        _render_blocks([c for c in part_el if _ln(c) in _BLOCK_TAGS], 2, out,
                       base_dir, images)
    return _Page(slug=pid, kind=kind, title=title, label=label,
                 body="".join(out), subnav=subnav)


def _abstract_page(abs_el) -> _Page:
    parts: list[str] = []
    for sec in abs_el.findall("sec"):
        label = _title_text(sec)
        for p in sec.findall("p"):
            run_in = f'<span class="abs-label">{_esc(label)}.</span> ' if label else ""
            parts.append(f'<p class="abstract-p">{run_in}{_inline(p)}</p>')
            label = ""  # only the first paragraph of a sec gets the run-in label
    return _Page(slug="abstract", kind="abstract", title="Abstract",
                 body="".join(parts))


def _reflist_page(rl) -> _Page:
    rid = rl.get("id", "ref-list1")
    title_el = rl.find("title")
    title = "".join(title_el.itertext()).strip() if title_el is not None else "References"
    items: list[str] = []
    for ref in rl.findall("ref"):
        anchor = f' id="{_esc(ref.get("id"))}"' if ref.get("id") else ""
        mc = ref.find("mixed-citation")
        text = _inline(mc) if mc is not None else _esc("".join(ref.itertext()).strip())
        items.append(f"<li{anchor}>{text}</li>")
    body = f'<ol class="ref-list">{"".join(items)}</ol>' if items else ""
    return _Page(slug=rid, kind="refs", title=title, body=body)


def _collect_pages(root, base_dir, images) -> list[_Page]:
    pages: list[_Page] = []
    m = _meta(root)

    if m["abstract"] is not None:
        pages.append(_abstract_page(m["abstract"]))

    fm = root.find("front-matter")
    if fm is not None:
        for part in fm:
            if _ln(part) in ("foreword", "front-matter-part", "ack", "dedication",
                             "preface", "book-part"):
                pages.append(_part_page(part, base_dir, images, kind="frontmatter"))

    bb = root.find("book-body")
    if bb is not None:
        for part in bb.findall("book-part"):
            pages.append(_part_page(part, base_dir, images, kind="chapter"))

    back = root.find("book-back")
    letters = iter(string.ascii_uppercase)
    if back is not None:
        for part in back:
            tag = _ln(part)
            if tag in ("book-app-group", "app-group"):
                for app in part:
                    if _ln(app) in ("book-app", "app"):
                        pages.append(_part_page(app, base_dir, images, kind="appendix",
                                                label=f"Appendix {next(letters)}"))
            elif tag in ("book-app", "app"):
                pages.append(_part_page(part, base_dir, images, kind="appendix",
                                        label=f"Appendix {next(letters)}"))
            elif tag == "ref-list":
                pages.append(_reflist_page(part))
            elif tag in ("ack", "glossary", "book-part"):
                pages.append(_part_page(part, base_dir, images, kind="chapter"))
    return pages


# ---------------------------------------------------------------------------
# Page fragments
# ---------------------------------------------------------------------------

def _page_article(page: _Page) -> str:
    label = f'<span class="label">{_esc(page.label)}</span> ' if page.label else ""
    h1 = (f'<div class="meta-content fm-sec"><h1 id="{_esc(page.slug)}">'
          f'{label}<span class="title">{_esc(page.title)}</span></h1></div>')
    inthis = ""
    subs = [(sid, stitle) for sid, stitle in page.subnav if sid and stitle]
    if len(subs) >= 2:
        lis = "".join(f'<li><a href="#{_esc(sid)}">{_esc(stitle)}</a></li>'
                      for sid, stitle in subs)
        inthis = ('<div class="bk-inthispage"><div class="bk-inthispage-h">'
                  f'In this Page</div><ul>{lis}</ul></div>')
    return (f'<article class="bk-page" data-slug="{_esc(page.slug)}" hidden>'
            f'{h1}{inthis}<div class="body-content whole_rhythm" itemprop="text">'
            f'{page.body}</div></article>')


def _contents_article(pages: list[_Page], m: dict) -> str:
    groups: list[tuple[str, list[_Page]]] = []
    order = [("Front matter", ("abstract", "frontmatter")),
             ("Report", ("chapter", "refs")),
             ("Appendices", ("appendix",))]
    for heading, kinds in order:
        members = [p for p in pages if p.kind in kinds]
        if members:
            groups.append((heading, members))
    blocks: list[str] = []
    for heading, members in groups:
        lis = []
        for p in members:
            lab = f'<span class="c-label">{_esc(p.label)}</span> ' if p.label else ""
            lis.append(f'<li class="c-{p.kind}"><a href="#{_esc(p.slug)}">'
                       f'{lab}{_esc(p.title)}</a></li>')
        blocks.append(f'<div class="c-group"><div class="c-group-h">{_esc(heading)}'
                      f'</div><ul class="bk-contents">{"".join(lis)}</ul></div>')
    return (f'<article class="bk-page" data-slug="contents" hidden>'
            f'<div class="meta-content"><h1 class="book-h1">{_esc(m["title"])}</h1>'
            f'<div class="book-h1-sub">Table of contents</div></div>'
            f'<div class="body-content">{"".join(blocks)}</div></article>')


def _secnav(chain: list[dict]) -> str:
    lis = []
    for p in chain:
        lab = f'<span class="n-label">{_esc(p["label"])}</span> ' if p["label"] else ""
        lis.append(f'<li data-slug="{_esc(p["slug"])}"><a href="#{_esc(p["slug"])}">'
                   f'{lab}{_esc(p["title"])}</a></li>')
    return '<ul class="bk-secnav">' + "".join(lis) + "</ul>"


def _views_panel(downloads: list[dict] | None) -> str:
    items = ['<li><a id="bk-print" href="#">Print this page</a></li>']
    for d in downloads or []:
        if d.get("href") and d.get("label"):
            items.append(f'<li><a href="{_esc(d["href"])}">{_esc(d["label"])}</a></li>')
    return '<ul class="rail-links">' + "".join(items) + "</ul>"


def _citation(m: dict) -> str:
    bits = [x for x in (m["publisher"], m["loc"], m["year"]) if x]
    src = ". ".join(bits)
    tail = f" {_esc(src)}." if src else ""
    return ("This is a preview of how the report will read on NCBI Bookshelf, "
            "generated by rlm-bmdx from the report&#8217;s BITS/JATS submission "
            f"XML.{tail}")


# ---------------------------------------------------------------------------
# Whole-book assembly
# ---------------------------------------------------------------------------

def _build_html(root, base_dir, images: dict | None, downloads: list[dict] | None) -> str:
    m = _meta(root)
    pages = _collect_pages(root, base_dir, images)

    # The navigation chain: Contents first, then every page.
    chain: list[dict] = [{"slug": "contents", "kind": "contents",
                          "title": "Contents", "label": ""}]
    chain += [{"slug": p.slug, "kind": p.kind, "title": p.title, "label": p.label}
              for p in pages]

    articles = _contents_article(pages, m) + "".join(_page_article(p) for p in pages)

    bits = [x for x in (m["publisher"], m["loc"], m["year"]) if x]
    if m["issn"]:
        bits.append(f"ISSN {m['issn']}")
    subtitle = " &#183; ".join(_esc(b) for b in bits)

    css = _stylesheet()
    js = _JS.replace("__CHAIN__", json.dumps(chain))
    return _PAGE_HEAD + f"""<style>{css}</style>
</head>
<body class="book-part">
<div class="preview-banner">Bookshelf-style preview &#8212; generated by rlm-bmdx from the report&#8217;s BITS XML. A content-only lookalike of the NCBI Bookshelf reader view; <strong>not</strong> an NCBI/NIEHS page.</div>
<header class="bk-masthead">
  <div class="bk-wordmark">Bookshelf<span class="bk-wordmark-sub">&#8201;&#183;&#8201;preview</span></div>
  <div class="bk-booktitle">{_esc(m["title"])}</div>
  <div class="bk-booksub">{subtitle}</div>
</header>
<div class="bk-container">
  <div class="bk-main" id="maincontent">
    <div class="pre-content"><div class="bk_prnt"><p class="small">{_citation(m)}</p></div></div>
    <div class="pagination bk-pager" id="bk-pager-top"></div>
    <div class="bk-pages">{articles}</div>
    <div class="pagination bk-pager" id="bk-pager-bottom"></div>
    <div class="post-content"><p class="small">Preview generated by rlm-bmdx from the report&#8217;s BITS/JATS &lt;book&gt; via rendering/bookshelf_preview.py. Not an NCBI/NIEHS page.</p></div>
  </div>
  <aside class="bk-rail" id="rightcolumn">
    <div class="rail-panel"><div class="rail-title">Views</div>{_views_panel(downloads)}</div>
    <div class="rail-panel"><div class="rail-title">Sections</div>{_secnav(chain)}</div>
  </aside>
</div>
<footer class="bk-footer">Rendered from BITS/JATS &lt;book&gt; &#8212; a content-only lookalike of the NCBI Bookshelf reader view. Approximate appearance; not an NCBI/NIEHS page.</footer>
<script>{js}</script>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def _parse(xml) -> etree._Element:
    parser = etree.XMLParser(load_dtd=False, no_network=True,
                             resolve_entities=False, recover=True)
    if isinstance(xml, str):
        xml = xml.encode("utf-8")
    return etree.fromstring(xml, parser)


def render_book_xml(xml, base_dir: Path | None = None,
                    images: dict | None = None,
                    downloads: list[dict] | None = None) -> str:
    """Render a BITS <book> (XML string or bytes) to a Bookshelf-style HTML page.

    `base_dir` roots relative figure `graphic` hrefs (a missing/absent image
    renders a visible placeholder rather than a broken link).  `images` is an
    optional {filename → base64-PNG} map that inlines figure images as data URIs
    so the page is self-contained — use chart_images(data) to build it from the
    session data (the BITS XML only carries the filename, not the bytes).
    `downloads` is an optional list of {label, href} rendered in the right-rail
    "Views" panel (the /Bookshelf page passes the PDF + DOCX links); omitted, the
    panel shows just "Print this page".
    """
    return _build_html(_parse(xml), base_dir, images, downloads)


def render_book_file(xml_path: Path) -> str:
    """Render a BITS <book> XML file to a Bookshelf-style HTML page."""
    xml_path = Path(xml_path)
    return render_book_xml(xml_path.read_bytes(),
                           base_dir=xml_path.resolve().parent)


def chart_images(data: dict) -> dict[str, str]:
    """Build the {filename → base64-PNG} map render_book_xml inlines, from a
    marshalled report `data` dict: every genomics chart carries its own
    `filename` + `png_b64` (genomics_charts.attach_genomics_charts).  Empty when
    the report has no charts (e.g. the shipped template ships `charts: []`)."""
    out: dict[str, str] = {}
    for entry in data.get("genomics_sections") or []:
        for chart in entry.get("charts") or []:
            fn, b64 = chart.get("filename"), chart.get("png_b64")
            if fn and b64:
                out[fn] = b64
    return out


def _stylesheet() -> str:
    """The inlined stylesheet: the vendored real Bookshelf CSS when present
    (assets/bookshelf/bookshelf.css), else the built-in eye-calibrated CSS."""
    try:
        if _VENDORED_CSS.exists():
            return _VENDORED_CSS.read_text(encoding="utf-8")
    except OSError:
        pass
    return _CSS


# ---------------------------------------------------------------------------
# Page shell + built-in CSS + navigation JS (reader-view lookalike, by eye)
# ---------------------------------------------------------------------------

_PAGE_HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bookshelf preview</title>
"""

_CSS = """
:root{
  --ink:#1a1a1a; --muted:#5c6670; --rule:#cfd6dd; --link:#0b6cb7;
  --accent:#2e6db4; --bg:#ffffff; --rail-bg:#f3f6f8; --grouprow:#eef2f5;
  --thead:#e9eef2; --banner:#fff8e1; --banner-br:#e6d48a; --hline:#97b0c8;
}
*{box-sizing:border-box;}
html,body{margin:0;padding:0;}
body{
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
  color:var(--ink); background:#fafbfc; line-height:1.55; font-size:16px;
  -webkit-font-smoothing:antialiased;
}
a{color:var(--link); text-decoration:none;}
a:hover{text-decoration:underline;}
[hidden]{display:none !important;}
.preview-banner{
  background:var(--banner); border-bottom:1px solid var(--banner-br);
  color:#5b4a00; font-size:12.5px; padding:7px 18px; text-align:center;
}
.bk-masthead{
  background:#fff; border-bottom:1px solid var(--rule); padding:14px 24px 12px;
}
.bk-wordmark{font-size:1.05rem; font-weight:800; color:#20558a; letter-spacing:.01em;}
.bk-wordmark-sub{font-weight:600; color:var(--muted); font-size:.85rem;}
.bk-booktitle{font-size:1.16rem; font-weight:700; color:#12263a; margin-top:6px; line-height:1.3;}
.bk-booksub{font-size:.8rem; color:var(--muted); margin-top:3px;}
.bk-container{
  display:flex; align-items:flex-start; gap:26px; max-width:1180px;
  margin:0 auto; padding:22px 24px 60px;
}
.bk-main{flex:1 1 auto; min-width:0; background:#fff; border:1px solid var(--rule);
  border-radius:6px; padding:26px 40px 40px;}
/* pre/post content (citation + provenance line) */
.pre-content .bk_prnt{border-bottom:1px solid #e6ebef; padding-bottom:12px; margin-bottom:6px;}
.pre-content .small,.post-content .small{font-size:.78rem; color:var(--muted); margin:0;}
.post-content{border-top:1px solid #e6ebef; margin-top:26px; padding-top:12px;}
/* pagination */
.pagination.bk-pager{display:flex; gap:8px; align-items:center; margin:14px 0;}
.pagination.bk-pager .page_link{
  display:inline-block; padding:4px 12px; border:1px solid var(--rule);
  border-radius:4px; background:#f6f8fa; color:var(--link); font-size:.86rem; font-weight:600;}
.pagination.bk-pager a.page_link:hover{background:#e9eff4; text-decoration:none;}
.pagination.bk-pager .page_link.contents{margin:0 auto; background:#fff; font-weight:700;}
.pagination.bk-pager .page_link.disabled{color:#a8b2ba; background:#f2f4f6; cursor:default;}
/* section title (meta-content) */
.meta-content{margin:0 0 4px;}
.meta-content h1{font-size:1.7rem; font-weight:700; color:#12263a; line-height:1.22;
  margin:6px 0 14px; padding-bottom:10px; border-bottom:2px solid #dbe2e8;}
.meta-content h1 .label{color:var(--muted); font-weight:700; font-size:1.02rem;
  display:block; margin-bottom:2px; text-transform:uppercase; letter-spacing:.05em;}
.book-h1{font-size:1.7rem; color:#12263a; margin:6px 0 2px;}
.book-h1-sub{color:var(--muted); font-size:.9rem; margin-bottom:16px;}
/* body content */
.body-content h2{font-size:1.3rem; font-weight:700; color:#1b3a4b; margin:26px 0 8px;
  padding-bottom:5px; border-bottom:1px solid var(--hline);}
.body-content h3{font-size:1.12rem; font-weight:700; color:#22333f; margin:22px 0 6px;}
.body-content h4{font-size:1.0rem; font-weight:700; color:#2a2a2a; margin:18px 0 6px;}
.body-content h5,.body-content h6{font-size:.96rem; font-weight:700; margin:14px 0 6px;}
.body-content p{margin:0 0 12px;}
.abstract-p{margin-bottom:10px;}
.abs-label{font-weight:700;}
sup{font-size:.72em;} sub{font-size:.72em;}
.xref{white-space:nowrap;}
/* "In this Page" mini-toc */
.bk-inthispage{float:right; width:250px; margin:0 0 14px 22px; border:1px solid var(--rule);
  border-radius:5px; background:#f7f9fb; padding:10px 12px; font-size:.85rem;}
.bk-inthispage-h{font-weight:700; color:#22333f; margin-bottom:6px; font-size:.8rem;
  text-transform:uppercase; letter-spacing:.04em;}
.bk-inthispage ul{list-style:none; margin:0; padding:0;}
.bk-inthispage li{margin:2px 0;}
/* tables (div.table › h3 › div.large_tbl › table.no_margin) */
.table{margin:22px 0 24px;}
.table>h3{font-size:1.0rem; font-weight:400; color:#1b3a4b; margin:0 0 8px; border:0;}
.table>h3 .label{font-weight:700; margin-right:.4em;}
.table>h3 .title{font-weight:400;}
.large_tbl{overflow-x:auto; border:1px solid var(--rule);}
table.no_margin{border-collapse:collapse; width:100%; font-size:.8rem; background:#fff;}
table.no_margin th, table.no_margin td{
  border:0; border-bottom:1px solid #e3e8ec; padding:5px 9px;
  text-align:right; vertical-align:top;}
table.no_margin thead th{
  background:var(--thead); border-bottom:2px solid #c7d0d7; font-weight:700;
  text-align:right; color:#22333f; position:sticky; top:0;}
table.no_margin td:first-child, table.no_margin th:first-child{text-align:left;}
table.no_margin tr td.grouprow{
  background:var(--grouprow); font-weight:700; text-align:left;
  color:#22333f; border-bottom:1px solid #c7d0d7;}
.temp-labeled-list{margin:8px 0 0; font-size:.78rem; color:var(--muted); line-height:1.45;}
.temp-labeled-list dt{display:none;}
.temp-labeled-list dd{margin:0;}
.temp-labeled-list p{margin:2px 0;}
/* figures */
.figure.bk_fig{margin:22px 0; text-align:center;}
.figure.bk_fig .graphic img{max-width:100%; height:auto; border:1px solid var(--rule);}
.figure.bk_fig .fig-missing{color:var(--muted); font-style:italic; padding:26px;
  border:1px dashed var(--rule); background:#fafbfc;}
.figure.bk_fig h3{font-size:.95rem; font-weight:700; color:#22333f; margin:8px 0 2px;}
.figure.bk_fig .caption{font-size:.86rem; color:#333; text-align:left;}
.figure.bk_fig .caption p{margin:4px 0;}
.boxed{border:1px solid var(--rule); background:#fafbfc; padding:12px 16px;
  margin:16px 0; border-radius:4px;}
ul.bk-list{margin:0 0 12px 22px;}
ol.ref-list{font-size:.9rem; line-height:1.5; padding-left:26px;}
ol.ref-list li{margin:0 0 8px;}
/* contents landing */
.c-group{margin:0 0 20px;}
.c-group-h{font-size:.78rem; font-weight:700; text-transform:uppercase; letter-spacing:.06em;
  color:var(--muted); border-bottom:1px solid var(--rule); padding-bottom:4px; margin-bottom:8px;}
ul.bk-contents{list-style:none; margin:0; padding:0;}
ul.bk-contents li{margin:5px 0; font-size:.98rem;}
ul.bk-contents .c-label{color:var(--muted); font-weight:600; margin-right:.4em;}
/* right rail */
.bk-rail{flex:0 0 260px; align-self:flex-start; position:sticky; top:14px;
  max-height:calc(100vh - 28px); overflow:auto;}
.rail-panel{border:1px solid var(--rule); border-radius:6px; overflow:hidden;
  background:#fff; margin-bottom:16px;}
.rail-title{background:var(--rail-bg); border-bottom:1px solid var(--rule);
  font-size:.72rem; font-weight:700; letter-spacing:.07em; text-transform:uppercase;
  color:var(--muted); padding:8px 12px;}
ul.rail-links,ul.bk-secnav{list-style:none; margin:0; padding:6px 0;}
ul.rail-links li,ul.bk-secnav li{margin:0;}
ul.rail-links a{display:block; padding:7px 14px; color:var(--link); font-size:.9rem;}
ul.rail-links a:hover{background:#eef2f5; text-decoration:none;}
ul.bk-secnav a{display:block; padding:5px 14px; color:#26424f; font-size:.85rem; line-height:1.35;}
ul.bk-secnav a:hover{background:#eef2f5; text-decoration:none;}
ul.bk-secnav .n-label{color:var(--muted); font-weight:600; margin-right:.3em;}
ul.bk-secnav li.current a{background:#e3ecf4; border-left:3px solid var(--accent);
  padding-left:11px; font-weight:600; color:#12263a;}
.bk-footer{border-top:1px solid var(--rule); color:var(--muted); font-size:12px;
  padding:16px 24px 40px; max-width:1180px; margin:0 auto; background:#fafbfc;}
@media (max-width:900px){
  .bk-container{flex-direction:column; padding:16px 14px 50px;}
  .bk-main{padding:18px 18px 30px; width:100%;}
  .bk-rail{position:static; flex-basis:auto; max-height:none; width:100%; order:3;}
  .bk-inthispage{float:none; width:auto; margin:0 0 14px;}
}
@media print{
  .preview-banner,.bk-rail,.pagination.bk-pager,.bk-inthispage{display:none !important;}
  .bk-page[hidden]{display:block !important;}
  .bk-main{border:0; padding:0;}
}
"""

_JS = """
(function(){
  var chain = __CHAIN__;
  var pages = {};
  document.querySelectorAll('.bk-page').forEach(function(el){
    pages[el.getAttribute('data-slug')] = el;
  });
  var idxBySlug = {};
  chain.forEach(function(p, i){ idxBySlug[p.slug] = i; });

  function pageElFor(id){
    var el = document.getElementById(id);
    while(el && el !== document.body){
      if(el.classList && el.classList.contains('bk-page')) return el;
      el = el.parentNode;
    }
    return null;
  }
  function updatePager(id, i){
    var el = document.getElementById(id); if(!el) return;
    var prev = i > 0 ? chain[i-1] : null;
    var next = i < chain.length - 1 ? chain[i+1] : null;
    var h = '';
    h += prev ? '<a class="active page_link prev" href="#' + prev.slug + '">&lt; Prev</a>'
              : '<span class="page_link prev disabled">&lt; Prev</span>';
    h += '<a class="page_link contents" href="#contents">Contents</a>';
    h += next ? '<a class="active page_link next" href="#' + next.slug + '">Next &gt;</a>'
              : '<span class="page_link next disabled">Next &gt;</span>';
    el.innerHTML = h;
  }
  function activate(slug, anchorId){
    if(!(slug in pages)) slug = chain[0].slug;
    var i = idxBySlug[slug];
    Object.keys(pages).forEach(function(s){ pages[s].hidden = (s !== slug); });
    updatePager('bk-pager-top', i);
    updatePager('bk-pager-bottom', i);
    document.querySelectorAll('.bk-secnav li').forEach(function(li){
      li.classList.toggle('current', li.getAttribute('data-slug') === slug);
    });
    if(anchorId){
      var a = document.getElementById(anchorId);
      if(a){ a.scrollIntoView(); } else { window.scrollTo(0, 0); }
    } else {
      window.scrollTo(0, 0);
    }
    var t = chain[i] && chain[i].title;
    document.title = (t || 'Contents') + ' \\u2014 Bookshelf preview';
  }
  function fromHash(){
    var h = (location.hash || '').replace(/^#/, '');
    if(!h){ activate(chain[0].slug); return; }
    if(h in pages){ activate(h); return; }
    var pe = pageElFor(h);
    if(pe){ activate(pe.getAttribute('data-slug'), h); return; }
    activate(chain[0].slug);
  }
  window.addEventListener('hashchange', fromHash);
  document.addEventListener('click', function(e){
    var a = e.target.closest ? e.target.closest('a[href^="#"]') : null;
    if(!a) return;
    var id = a.getAttribute('href').slice(1);
    if(!id || id in pages) return;   // page-slug links: let hashchange handle
    var pe = pageElFor(id);
    if(pe){ e.preventDefault(); location.hash = '#' + id; }
  });
  var pb = document.getElementById('bk-print');
  if(pb) pb.addEventListener('click', function(e){ e.preventDefault(); window.print(); });
  fromHash();
})();
"""
