r"""
test_docx_generator.py — smoke + structural tests for docx_generator (ADR-0008
Option B, the third render surface).

What this proves
----------------
  - generate_docx returns bytes that python-docx can re-open (a valid .docx).
  - The document has the expected structure: the title-page title line, section
    headings from DOCUMENT_TREE, roman→arabic two-section page numbering, and
    at least one rendered table.
  - Rich session data (loaded from the DTXSID50469320 session via the same
    load_session_data path the LaTeX export uses) renders its apical / genomics
    / BMD-summary tables — the shared render_common EXTRACT plans the docx
    handlers consume produce real Word tables, not just placeholders.
  - The dispatch table covers every registered node type (the import-time
    assert_dispatch_covers has teeth — re-checked here explicitly).

What this does NOT prove
------------------------
  - Visual fidelity in Word / LibreOffice — that's a manual review step.
"""

import re
from io import BytesIO
from pathlib import Path

import pytest
from docx import Document
from docx.shared import Inches, Pt

from rendering.docx_generator import _DISPATCH, generate_docx
from rendering.latex_export import load_session_data
from rendering.render_common import RENDERABLE_NODE_TYPES
from rendering.report_data import scaffold_report_data


REPO_ROOT = Path(__file__).resolve().parents[2]
SESSION_DTXSID = "DTXSID50469320"
SESSION_DIR = REPO_ROOT / "sessions" / SESSION_DTXSID


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def scaffold() -> dict:
    """The full NIEHS scaffold — complete structure, placeholder content."""
    return scaffold_report_data(
        chemical_name="Perfluorohexanesulfonamide",
        casrn="41997-13-1",
        dtxsid=SESSION_DTXSID,
    )


@pytest.fixture(scope="module")
def rich() -> dict:
    """
    A content-rich, render-ready data dict from the real DTXSID50469320 session
    — the SAME load_session_data path the LaTeX/Overleaf export uses, so this is
    a valid render INPUT (unlike the marshal_rich fixture, which is a marshal
    OUTPUT and not shaped for the renderers).
    """
    if not SESSION_DIR.exists():
        pytest.skip(f"session {SESSION_DTXSID} not present")
    return load_session_data(
        SESSION_DTXSID,
        chemical_name="Perfluorohexanesulfonamide",
        casrn="41997-13-1",
    )


def _open(docx_bytes: bytes) -> Document:
    """Re-open generated bytes as a Document (fails if the .docx is invalid)."""
    return Document(BytesIO(docx_bytes))


def _all_text(doc: Document) -> str:
    """Every paragraph's text joined — for substring assertions."""
    return "\n".join(p.text for p in doc.paragraphs)


# ---------------------------------------------------------------------------
# Structural smoke
# ---------------------------------------------------------------------------

def test_dispatch_covers_every_registered_type():
    """Every canonical node type has a Word emitter (import-time guarantee)."""
    assert set(_DISPATCH) == set(RENDERABLE_NODE_TYPES)


def test_generates_valid_docx(scaffold):
    """Output is bytes that python-docx can re-open."""
    out = generate_docx(scaffold)
    assert isinstance(out, bytes) and len(out) > 0
    doc = _open(out)  # raises if the OOXML is malformed
    assert len(doc.paragraphs) > 0


def test_title_page_line_present(scaffold):
    """The title page (not the cover) renders the NIEHS title line + chemical."""
    doc = _open(generate_docx(scaffold))
    text = _all_text(doc)
    assert "NIEHS Report on the" in text
    assert "Perfluorohexanesulfonamide" in text


def test_title_page_matches_reference_spec(scaffold):
    """
    On the template-base path the title line carries the reference's NATIVE NTP
    title style (1-03_Report_Title) — its typography (Arial Bold 20pt black) is
    inherited from that style, not set on the run.  Assert the style resolves.
    """
    doc = _open(generate_docx(scaffold))
    title_para = next(
        p for p in doc.paragraphs if p.text.startswith("NIEHS Report on the")
    )
    assert title_para.style.name == "1-03_Report_Title"


def test_title_page_is_one_paragraph_per_role(scaffold):
    """
    The title block is ONE multi-line paragraph (line breaks, matching the
    reference's single `1-03_Report_Title` paragraph), NOT one paragraph per
    line — the old shape stacked Normal `space_after` gaps between every line.
    """
    doc = _open(generate_docx(scaffold))
    title_paras = [
        p for p in doc.paragraphs if p.text.startswith("NIEHS Report on the")
    ]
    assert len(title_paras) == 1, "the title should be a single paragraph"
    # The 7 title lines are carried as line breaks within that one paragraph.
    assert title_paras[0]._p.xml.count("<w:br/>") >= 1


def test_publisher_block_uses_native_roles(scaffold):
    """The publisher block lines each carry their NTP native paragraph style from
    the template base (1-01_Publisher_Name / 1-08_Publication_Institute /
    1-09_Publication_Department / NTP Publisher Location), so their tight spacing
    is inherited from the reference styles rather than set programmatically."""
    doc = _open(generate_docx(scaffold))

    def _para(startswith):
        return next(p for p in doc.paragraphs if p.text.startswith(startswith))

    assert _para("National Institute of Environmental").style.name == "1-01_Publisher_Name"
    assert _para("Public Health Service").style.name == "1-08_Publication_Institute"
    assert _para("U.S. Department of Health").style.name == "1-09_Publication_Department"
    assert _para("Research Triangle Park").style.name == "NTP Publisher Location"
    assert _para("ISSN:").style.name == "1-05c_ISSN"


def test_title_page_role_styling_applied(scaffold):
    """
    A `styles.title_page` config styles each ROLE independently: `report_title`
    can be re-fonted/sized while `publisher_name` gets italic, and other roles
    keep the reference default.  Proves per-role styling reaches the page.
    """
    data = dict(scaffold)
    data["layout_style"] = {
        "title_page": {
            "report_title": {"font": "Times New Roman", "font_size": "28pt",
                             "weight": "bold"},
            "publisher_name": {"style": "italic"},
        }
    }
    doc = _open(generate_docx(data))
    title = next(r for p in doc.paragraphs for r in p.runs
                 if r.text.strip() == "NIEHS Report on the")
    assert title.font.name == "Times New Roman"
    assert title.font.size == Pt(28)
    # publisher name (institution line) is italic; a non-styled role is not.
    pub = next(r for p in doc.paragraphs for r in p.runs
               if r.text.startswith("National Institute of Environmental"))
    assert pub.font.italic is True


def test_title_page_empty_config_unchanged(scaffold):
    """No title_page config ⇒ the title paragraph uses the NTP native title style
    (1-03_Report_Title) from the base, unmodified — the no-drift guarantee (the
    typography is inherited from that style, not set on the run)."""
    doc = _open(generate_docx(scaffold))
    title_para = next(
        p for p in doc.paragraphs if p.text.startswith("NIEHS Report on the")
    )
    assert title_para.style.name == "1-03_Report_Title"


def test_front_matter_headings_match_reference_body_left(scaffold):
    """Every front-matter section header (Foreword, Table of Contents, Tables,
    About, Peer Review, etc.) gets the SAME reference front-matter heading look —
    Arial 16pt bold, CENTERED, 12pt after (1-23_FrontMatter_Head1) — so they are
    uniform (no one header bigger/tighter than the rest).  Body section headings
    (Background, Summary, References — `narrative` nodes routing through the same
    renderer) stay as the left-aligned built-in Heading 1, matching the NTP
    reference's left body heads."""
    doc = _open(generate_docx(scaffold))
    front = {"Foreword", "About This Report", "Peer Review",
             "Publication Details", "Acknowledgments", "Abstract"}
    body = {"Background", "Materials and Methods", "Results", "Summary", "References"}
    for p in doc.paragraphs:
        t = p.text.strip()
        if t in front:
            # A real NTP front-matter style (the 1-NN family, or a named NTP head).
            name = p.style.name
            assert name.startswith("1-") or "Head" in name, (
                f"{t!r} front-matter header uses {name!r}, not an NTP front style"
            )
        elif t in body:
            assert p.style.name == "3-02a_Head1_NoNumber", (
                f"{t!r} body heading uses {p.style.name!r}, expected 3-02a_Head1_NoNumber"
            )


def test_no_green_accent_bar_table(scaffold):
    """
    The page-1 cover (with its green accent bar) is excluded on the docx surface,
    so there must be NO 1x1 shaded bar table — the first table is a real data
    table, and no cell carries the cover green fill.
    """
    doc = _open(generate_docx(scaffold))
    # No 1x1 table (the old _add_cover_bar shape).
    assert all(not (len(t.rows) == 1 and len(t.columns) == 1) for t in doc.tables)
    # No cell shaded with the cover green anywhere.
    xml = "".join(t._tbl.xml for t in doc.tables)
    assert "78A12E" not in xml and "78a12e" not in xml


def test_section_headings_present(scaffold):
    """Headings derived from DOCUMENT_TREE appear as NTP section-heading styles.

    On the template-base path the section headings carry the reference's native
    NTP styles (3-02a/3-03a/3-04a_Head*_NoNumber), not the built-in "Heading N".
    """
    doc = _open(generate_docx(scaffold))
    heading_texts = [
        p.text for p in doc.paragraphs
        if (p.style and ("Head" in p.style.name or p.style.name.startswith("Heading")))
    ]
    joined = "\n".join(heading_texts)
    assert "Background" in joined
    assert heading_texts, "no heading-styled paragraphs were emitted"


def test_roman_then_arabic_numbering_across_flow_sections(scaffold):
    """
    Front matter is lower-roman, the body restarts at arabic 1.  The document is
    split into more sections than that because (a) orientable landscape nodes
    lower into their own page-geometry sections (FLOW islands, REGION-TRANSPARENT
    — no <w:pgNumType>, so the arabic counter flows through), and (b) each
    back-matter appendix opens its OWN page-numbering region.

    So the NUMBERED sections, in document order, are: the front (lowerRoman), the
    body-start (decimal), then one decimal+chapStyle section per appendix (A-1,
    B-1, …).  The FLOW islands + portrait resumes carry no pgNumType.
    """
    from docx.oxml.ns import qn as _qn
    doc = _open(generate_docx(scaffold))
    numbered = []
    for section in doc.sections:
        pgNumType = section._sectPr.find(_qn("w:pgNumType"))
        if pgNumType is not None:
            numbered.append((pgNumType.get(_qn("w:fmt")),
                             pgNumType.get(_qn("w:chapStyle"))))
    # Front roman + body decimal (neither chapter-relative)…
    assert numbered[0] == ("lowerRoman", None)
    assert numbered[1] == ("decimal", None)
    # …then six chapter-relative appendix sections (A–F).
    appendix_numbered = numbered[2:]
    assert len(appendix_numbered) == 6
    assert all(fmt == "decimal" and chap == "1" for fmt, chap in appendix_numbered)


def test_landscape_nodes_lower_into_transparent_sections(scaffold):
    """
    FLOW axis → Word sections.  Orientable nodes marked landscape lower into
    their own page-geometry section; a maximal contiguous run of same-orientation
    nodes coalesces into ONE section (per-node FLOW → per-region Word construct).
    Each landscape island is region-transparent: it swaps pgSz to landscape
    dimensions but declares NO pgNumType and NO footerReference, so the body's
    page numbering and running footer flow through it unbroken — exactly how the
    NIEHS-10 reference encodes its wide-table spreads.

    Every portrait section keeps portrait dimensions (12240 wide); a resumed
    portrait section after a landscape run must NOT inherit the landscape
    orientation flag its sectPr was cloned from.
    """
    from docx.oxml.ns import qn as _qn
    doc = _open(generate_docx(scaffold))

    landscape = []
    for s in doc.sections:
        pg = s._sectPr.find(_qn("w:pgSz"))
        orient = pg.get(_qn("w:orient"))
        width = int(pg.get(_qn("w:w")))
        if orient == "landscape":
            landscape.append(s)
            # Landscape geometry: US-Letter rotated (15840 × 12240).
            assert width == 15840
            # Region-transparent: no own page numbering, no own footer.
            assert s._sectPr.find(_qn("w:pgNumType")) is None
            assert s._sectPr.find(_qn("w:footerReference")) is None
        else:
            # A portrait section (incl. a resume after a landscape run) keeps
            # portrait dimensions and no lingering landscape orient flag.
            assert orient is None
            assert width == 12240

    # The scaffold carries orientable landscape tables, so at least one island
    # must have formed (guards against the lowering silently no-op-ing).
    assert landscape, "expected at least one landscape section from orientable nodes"


def test_each_appendix_opens_a_chapter_relative_section(scaffold):
    """Each back-matter appendix (A–F) lowers into its OWN page-numbering region:
    a Word section carrying <w:pgNumType w:start="1" w:chapStyle="1"/>.  chapStyle
    reuses the level-1 appendix head's upperLetter list number (A/B/C…) as the
    page-number chapter prefix, so pages read "A-1, B-1, …" (the reference's
    appendix numbering).  The appendix heading paragraph uses the numbered
    4-05_Appendix_Head_1 style with a BARE title run (the list supplies the
    "Appendix A." prefix)."""
    from docx.oxml.ns import qn as _qn
    doc = _open(generate_docx(scaffold))

    chap_sections = [
        s for s in doc.sections
        if (pn := s._sectPr.find(_qn("w:pgNumType"))) is not None
        and pn.get(_qn("w:chapStyle")) == "1"
    ]
    # Six appendices A–F, each its own chapter-relative section.
    assert len(chap_sections) == 6
    for s in chap_sections:
        pn = s._sectPr.find(_qn("w:pgNumType"))
        assert pn.get(_qn("w:start")) == "1"
        assert pn.get(_qn("w:fmt")) == "decimal"

    # The front/body sections must NOT be chapter-relative (no stray chapStyle
    # cloned from the base sectPr).
    front = doc.sections[0]._sectPr.find(_qn("w:pgNumType"))
    assert front.get(_qn("w:chapStyle")) is None
    assert front.get(_qn("w:fmt")) == "lowerRoman"

    # Appendix TITLES use the numbered "Heading 1" style (numId 8, ilvl 0 →
    # "Appendix A.") with a BARE-title run — the reference's mechanism.  (NOT
    # 4-05_Appendix_Head_1, which is the appendix SUB-heading, numId 8 ilvl 1 →
    # "A.1.".)  The list supplies the "Appendix A." prefix and the chapter letter
    # chapStyle reads, so the run text is just the descriptive title.
    appendix_heads = [
        p for p in doc.paragraphs
        if p.style is not None and p.style.name == "Heading 1"
    ]
    assert len(appendix_heads) == 6
    # Bare descriptive title — no literal "Appendix A." baked in.
    assert not any(p.text.strip().startswith("Appendix ") for p in appendix_heads)


def test_body_section_has_no_distinct_first_page(scaffold):
    """The front section suppresses its header on the cover via different-first-
    page; add_section() copies that flag onto the body section, but the body has
    no cover — leaving an empty, editable first-page header on page 1 of the body
    (a stray 'add header' control).  The body section must turn it back off."""
    from docx.oxml.ns import qn as _qn
    doc = _open(generate_docx(scaffold))
    body = doc.sections[-1]
    assert body.different_first_page_header_footer is False
    # And no <w:titlePg> lingers in the body sectPr.
    assert body._sectPr.find(_qn("w:titlePg")) is None


def test_has_tables(scaffold):
    """At least the sample-counts / roster tables render as Word tables."""
    doc = _open(generate_docx(scaffold))
    assert len(doc.tables) > 0


# ---------------------------------------------------------------------------
# Reference typography — the measured NIEHS spec is bound onto the base styles
# (see docx_generator Constants + _build_style_skeleton).  These lock the fonts
# and geometry so a regression in the style sheet fails loudly.
# ---------------------------------------------------------------------------

def _docdefault_font(doc):
    """(ascii-font, half-point-size) from the doc's rPrDefault — the reference
    carries the base body font at docDefaults, NOT on the Normal style."""
    dd = doc.styles.element.find(qn("w:docDefaults"))
    rpr = dd.find(qn("w:rPrDefault") + "/" + qn("w:rPr")) if dd is not None else None
    if rpr is None:
        return None, None
    rf = rpr.find(qn("w:rFonts"))
    sz = rpr.find(qn("w:sz"))
    return (rf.get(qn("w:ascii")) if rf is not None else None,
            sz.get(qn("w:val")) if sz is not None else None)


def test_body_font_is_times_12pt_via_docdefaults(scaffold):
    """The body font is Times New Roman 12pt — carried at the reference's
    docDefaults level (the template base), not set directly on Normal (which
    inherits it, so Normal.font.name reads None)."""
    doc = _open(generate_docx(scaffold))
    font, half_pt = _docdefault_font(doc)
    assert font == "Times New Roman"
    assert half_pt == "24"  # 24 half-points = 12pt


def test_section_heading_styles_are_bold_sized(scaffold):
    """Section headings use the NTP native styles (3-02a/3-03a/3-04a_Head*_NoNumber)
    at the reference sizes (17/15/13pt) and bold — inherited from the template
    base, not re-derived in Python."""
    doc = _open(generate_docx(scaffold))
    expected = {"3-02a_Head1_NoNumber": 17, "3-03a_Head2_NoNumber": 15,
                "3-04a_Head3_NoNumber": 13}
    for name, pt in expected.items():
        style = doc.styles[name]
        assert style.font.bold is True, f"{name} bold"
        assert style.font.size == Pt(pt), f"{name} size"


def test_running_header_style_present(scaffold):
    """The running-header style (Header / header) exists in the template base."""
    doc = _open(generate_docx(scaffold))
    names = {s.name for s in doc.styles}
    assert "Header" in names or "header" in names


def test_docdefaults_spacing_is_fully_neutralized(scaffold):
    """python-docx ships docDefaults pPr spacing (line=276 / 1.15x + after=200 /
    10pt); we remove the whole element so the document root is spacing-neutral like
    the NTP reference (whose docDefaults has NO spacing).  Every gap then comes
    from a style's own space_before/after — so the title renders single-spaced AND
    a hand-inserted paragraph does not inherit a phantom 10pt gap (ADR-0010)."""
    from docx.oxml.ns import qn
    doc = _open(generate_docx(scaffold))
    spacing = doc.styles.element.find(
        "/".join(qn(t) for t in ("w:docDefaults", "w:pPrDefault", "w:pPr", "w:spacing"))
    )
    assert spacing is None, "docDefaults pPr spacing should be removed entirely"


def test_section_margins_are_one_inch(scaffold):
    """US-Letter with 1" margins all round (the reference trim)."""
    doc = _open(generate_docx(scaffold))
    for section in doc.sections:
        assert section.left_margin == Inches(1)
        assert section.right_margin == Inches(1)
        assert section.top_margin == Inches(1)
        assert section.bottom_margin == Inches(1)


def test_table_cells_render_below_body_size(scaffold):
    """
    Table cell runs are set to the table size (10pt), one step below the 12pt
    body — so dense tables don't inherit the body size.  Header cells are Arial.
    """
    doc = _open(generate_docx(scaffold))
    # Find a table with a populated data row + header.
    for t in doc.tables:
        if len(t.rows) < 2 or not t.rows[0].cells[0].paragraphs[0].runs:
            continue
        hrun = t.rows[0].cells[0].paragraphs[0].runs[0]
        assert hrun.font.size == Pt(10)
        assert hrun.font.name == "Arial"
        # A data-row run (skip merged sex-separator rows, which have one cell).
        for r in t.rows[1:]:
            runs = r.cells[-1].paragraphs[0].runs
            if runs:
                assert runs[0].font.size == Pt(10)
                return
    pytest.skip("no populated table with header + data row found")


# ---------------------------------------------------------------------------
# Per-node layout styling — the docx twin of the CSS/LaTeX translators.  A
# `styles` block with per-type/per-instance specs applies to the paragraphs the
# matching node emitted, overlaying the base Normal/Heading styles.
# ---------------------------------------------------------------------------

def test_per_type_layout_style_applies_to_matching_nodes(scaffold):
    """A `types` entry restyles every node of that type (font/size/color)."""
    data = dict(scaffold)
    data["layout_style"] = {
        "types": {"narrative": {"font": "Georgia", "font_size": "14pt",
                                "color": "#cc0000"}}
    }
    doc = _open(generate_docx(data))
    styled = [
        r for p in doc.paragraphs for r in p.runs
        if r.font.name == "Georgia" and r.font.size == Pt(14)
    ]
    assert styled, "no narrative runs picked up the per-type font/size"
    assert str(styled[0].font.color.rgb) == "CC0000"


def test_instance_layer_wins_over_type_layer_in_docx(scaffold):
    """An `instances` entry overrides the `types` layer for one node id."""
    data = dict(scaffold)
    data["layout_style"] = {
        "types": {"narrative": {"weight": "normal"}},
        "instances": {"background": {"weight": "bold"}},
    }
    doc = _open(generate_docx(data))
    # The Background heading run must be bold (instance layer), proving the
    # instance override reached the docx surface.
    bg = [p for p in doc.paragraphs if p.text.strip() == "Background"]
    assert bg and any(r.font.bold for r in bg[0].runs)


def test_no_layout_style_is_a_noop(scaffold):
    """A document with no `layout_style` renders (base styles only, no crash)."""
    data = dict(scaffold)
    data.pop("layout_style", None)
    doc = _open(generate_docx(data))
    assert len(doc.paragraphs) > 0


def test_text_transform_uppercase_sets_all_caps(scaffold):
    """text_transform: uppercase → w:caps (all_caps) on the node's runs — a
    DISPLAY transform, so the underlying text is unchanged (round-trippable)."""
    data = dict(scaffold)
    data["layout_style"] = {"types": {"narrative": {"text_transform": "uppercase"}}}
    doc = _open(generate_docx(data))
    bg = [p for p in doc.paragraphs if p.text.strip() == "Background"]
    assert bg, "Background heading not found"
    # The run carries all_caps, and the stored text is NOT mutated to uppercase.
    assert any(r.font.all_caps for r in bg[0].runs)
    assert bg[0].text.strip() == "Background"


def test_letter_spacing_sets_rpr_spacing_in_twips(scaffold):
    """letter_spacing → rPr <w:spacing w:val> in twips (pt*20), on the CHARACTER
    element (rPr), not paragraph spacing (pPr)."""
    from docx.oxml.ns import qn

    data = dict(scaffold)
    data["layout_style"] = {"types": {"narrative": {"letter_spacing": "1.5pt"}}}
    doc = _open(generate_docx(data))
    bg = [p for p in doc.paragraphs if p.text.strip() == "Background"]
    assert bg, "Background heading not found"
    run = bg[0].runs[0]
    sp = run._element.get_or_add_rPr().find(qn("w:spacing"))
    assert sp is not None, "no rPr w:spacing emitted"
    assert sp.get(qn("w:val")) == "30"  # 1.5pt * 20 twips/pt


def test_letter_spacing_relative_unit_is_ignored(scaffold):
    """em/ex can't resolve to a fixed width without a size → no w:spacing (parity
    with the LaTeX surface, which also rejects relative units)."""
    from docx.oxml.ns import qn

    data = dict(scaffold)
    data["layout_style"] = {"types": {"narrative": {"letter_spacing": "0.2em"}}}
    doc = _open(generate_docx(data))
    bg = [p for p in doc.paragraphs if p.text.strip() == "Background"]
    run = bg[0].runs[0]
    rpr = run._element.find(qn("w:rPr"))
    sp = rpr.find(qn("w:spacing")) if rpr is not None else None
    assert sp is None


def test_break_before_and_after_apply_once_at_node_boundary(scaffold):
    """break_before sets pageBreakBefore on the node's FIRST paragraph; break_after
    appends a page-break run on its LAST — once each, not per paragraph (parity
    with HTML's one wrapping div and LaTeX's one \\clearpage)."""
    from docx.enum.text import WD_BREAK
    from docx.oxml.ns import qn

    data = dict(scaffold)
    # background is a narrative node; style the whole type so we can find its paras.
    data["layout_style"] = {
        "types": {"narrative": {"break_before": "page", "break_after": "page"}}
    }
    doc = _open(generate_docx(data))
    paras = doc.paragraphs
    heads = [i for i, p in enumerate(paras) if p.text.strip() == "Background"]
    assert heads, "Background heading not found"
    start = heads[0]
    # First paragraph of the node carries pageBreakBefore.
    assert paras[start].paragraph_format.page_break_before is True
    # It is set ONCE: the immediately-following paragraphs of the same node do not
    # all carry it (the old per-paragraph bug would set it on every paragraph).
    assert paras[start + 1].paragraph_format.page_break_before in (None, False)
    # A page-break run exists in the document (break_after emits a trailing break).
    break_runs = [
        br for p in paras for r in p.runs
        for br in r._element.findall(qn("w:br"))
        if br.get(qn("w:type")) == "page"
    ]
    assert break_runs, "break_after did not emit a page-break run"


def test_document_level_block_drives_page_and_base_fonts(scaffold):
    """The styles.document block overrides page geometry + base body/header fonts."""
    data = dict(scaffold)
    data["layout_style"] = {"document": {
        "page_width": "8.27in", "page_height": "11.69in",   # A4
        "margin_left": "1.25in",
        "default_font": "Palatino Linotype", "default_font_size": "11pt",
        "header_font": "Cambria",
    }}
    doc = _open(generate_docx(data))
    s = doc.sections[0]
    assert round(s.page_width.inches, 2) == 8.27
    assert round(s.page_height.inches, 2) == 11.69
    assert round(s.left_margin.inches, 2) == 1.25
    assert doc.styles["Normal"].font.name == "Palatino Linotype"
    assert doc.styles["Normal"].font.size == Pt(11)
    assert doc.styles["Header"].font.name == "Cambria"


def test_absent_document_block_uses_reference_constants(scaffold):
    """No document block ⇒ the reference defaults from the template base
    (US-Letter, Times 12 carried at docDefaults, not on Normal directly)."""
    data = dict(scaffold)
    data.pop("layout_style", None)
    doc = _open(generate_docx(data))
    s = doc.sections[0]
    assert round(s.page_width.inches, 2) == 8.5
    assert round(s.page_height.inches, 2) == 11.0
    font, half_pt = _docdefault_font(doc)
    assert font == "Times New Roman"
    assert half_pt == "24"  # 12pt


# ---------------------------------------------------------------------------
# Rich-data rendering — the shared EXTRACT plans produce real tables
# ---------------------------------------------------------------------------

def test_rich_data_renders_at_least_as_many_tables_as_scaffold(scaffold, rich):
    """
    A content-rich session dict must render at least as many tables as the
    placeholder scaffold, and a healthy number overall — proof the apical /
    genomics / BMD-summary plans actually emit Word tables when data is present.
    """
    scaffold_doc = _open(generate_docx(scaffold))
    rich_doc = _open(generate_docx(rich))
    assert len(rich_doc.tables) >= len(scaffold_doc.tables)
    assert len(rich_doc.tables) >= 5


def test_rich_data_renders_without_error(rich):
    """The full rich fixture renders end-to-end and re-opens cleanly."""
    doc = _open(generate_docx(rich))
    assert len(doc.paragraphs) > 0
    # The running header falls back through running_header/title — the rich
    # fixture sets a title, so it must not be the bare placeholder.
    assert _all_text(doc)


# ---------------------------------------------------------------------------
# Table of Contents — a NATIVE Word TOC field (page numbers + dot leaders are
# filled by Word/LibreOffice on open; a static paragraph list cannot carry them)
# ---------------------------------------------------------------------------

from docx.oxml.ns import qn  # noqa: E402


def test_toc_is_a_native_field(scaffold):
    """The Contents page emits a { TOC } field, not a static list."""
    doc = _open(generate_docx(scaffold))
    instrs = [e.text for e in doc.element.body.findall(".//" + qn("w:instrText"))]
    assert any(i and i.strip().startswith("TOC") for i in instrs)
    # \o "1-3" (levels), \h (hyperlinks), \u (use applied outline levels).
    toc = next(i for i in instrs if i and i.strip().startswith("TOC"))
    assert '\\o "1-3"' in toc and "\\h" in toc and "\\u" in toc


def test_toc_field_marks_document_fields_dirty(scaffold):
    """updateFields=true is set so Word offers to refresh the field on open.  This
    is NOT sufficient on its own for LibreOffice (which ignores it for Word-origin
    TOC fields) — the pre-populated cached entries are what guarantee a non-empty
    TOC either way (see test_toc_field_is_prepopulated)."""
    doc = _open(generate_docx(scaffold))
    uf = doc.settings.element.find(qn("w:updateFields"))
    assert uf is not None and uf.get(qn("w:val")) == "true"


def test_toc_field_is_prepopulated_with_entries(rich):
    """The TOC field carries CACHED entry paragraphs (TOC 1/2/3) between its
    separate and end marks, so the document opens showing a real contents list —
    not a bare placeholder — even in a reader that doesn't auto-update the field.
    The field stays live (begin/separate/end intact) so a refresh recomputes page
    numbers."""
    doc = _open(generate_docx(rich))
    # Every field in the body is well-formed: begin/separate/end are balanced
    # (the doc now carries several — the TOC, the Tables TOF, and per-table SEQ).
    kinds = [
        fc.get(qn("w:fldCharType"))
        for fc in doc.element.body.findall(".//" + qn("w:fldChar"))
    ]
    assert kinds.count("begin") == kinds.count("end") == kinds.count("separate")
    # The TOC field's instruction is present.
    instrs = [i.text for i in doc.element.body.findall(".//" + qn("w:instrText"))]
    assert any(i and i.strip().startswith('TOC \\o "1-3"') for i in instrs)
    # Real entry paragraphs styled TOC N follow the Contents heading.
    toc_i = next(i for i, p in enumerate(doc.paragraphs)
                 if p.text.strip() == "Table of Contents")
    entries = []
    for p in doc.paragraphs[toc_i + 1:]:
        if not p.style.name.lower().startswith("toc "):
            break
        entries.append(p)
    assert len(entries) >= 10
    # The first entry is the Foreword (front matter leads the tree).
    assert entries[0].text.startswith("Foreword")
    # Levels map to toc 1/2/3 (a level-2 heading like Study Design → toc 2).
    assert any(p.style.name.lower() == "toc 2" for p in entries)


def test_toc_entries_carry_pageref_fields_anchored_to_heading_bookmarks(rich):
    """Each cached TOC entry's page number is a `PAGEREF _Toc_<id> \\h` FIELD (not
    a literal placeholder), and a matching `<w:bookmarkStart w:name="_Toc_<id>">`
    sits on the target heading.  This is what lets Word for Web resolve each entry
    to its OWN page on refresh — without it the reader collapses every entry to a
    single page.  The anchors must match the bookmarks 1:1 (no dangling ref)."""
    doc = _open(generate_docx(rich))
    body = doc.element.body
    instrs = [i.text or "" for i in body.findall(".//" + qn("w:instrText"))]
    pagerefs = {
        m.group(1)
        for t in instrs
        if (m := re.search(r"PAGEREF (_Toc_\S+) \\h", t))
    }
    bookmarks = {
        bs.get(qn("w:name"))
        for bs in body.findall(".//" + qn("w:bookmarkStart"))
        if (bs.get(qn("w:name")) or "").startswith("_Toc_")
    }
    # There is at least one appendix entry, and its PAGEREF resolves.
    assert "_Toc_appendix-a" in pagerefs
    # Every PAGEREF anchor has a real bookmark target (no dangling reference).
    assert pagerefs, "expected PAGEREF fields in the TOC"
    assert pagerefs <= bookmarks, f"dangling anchors: {pagerefs - bookmarks}"
    # Entries are hyperlinks to those anchors (clickable + \\h).
    anchors = {
        h.get(qn("w:anchor"))
        for h in body.findall(".//" + qn("w:hyperlink"))
        if (h.get(qn("w:anchor")) or "").startswith("_Toc_")
    }
    assert "_Toc_appendix-a" in anchors


def test_toc_field_closes_with_trailing_empty_paragraph(rich):
    """The TOC field ends on a TRAILING EMPTY paragraph carrying the `end` fldChar,
    not on the last entry — matching the reference.  Two effects: the field's
    cached span (and its gray field-shading) extends one line past the last entry,
    and that empty paragraph is the gap before the next section header (without it
    the following heading jams against the last entry)."""
    doc = _open(generate_docx(rich))
    paras = doc.paragraphs
    toc_i = next(i for i, p in enumerate(paras) if p.text.strip() == "Table of Contents")
    # Last TOC-N entry, then the closer.  Entries use the reference's lowercase
    # built-in `toc 1/2/3` names (from the template base), not title-case "TOC N".
    def _is_toc_entry(p):
        return p.style.name.lower().startswith("toc ")
    last = None
    for j in range(toc_i + 1, len(paras)):
        if _is_toc_entry(paras[j]):
            last = j
        elif last is not None:
            break
    closer = paras[last + 1]
    assert closer.text.strip() == "", "field should close on an EMPTY paragraph"
    assert not _is_toc_entry(closer), "closer is a plain para, not a TOC entry"
    ends = closer._p.findall(".//" + qn("w:fldChar") + "[@" + qn("w:fldCharType") + "='end']")
    assert ends, "the closing empty paragraph must carry the field `end`"


def test_toc_entries_have_dot_leader_tab(rich):
    """Each cached TOC entry carries a right-aligned dotted-leader tab stop at the
    text-block edge — the classic dotted TOC line the reference uses."""
    from docx.enum.text import WD_TAB_ALIGNMENT, WD_TAB_LEADER
    doc = _open(generate_docx(rich))
    toc_i = next(i for i, p in enumerate(doc.paragraphs)
                 if p.text.strip() == "Table of Contents")
    first_entry = doc.paragraphs[toc_i + 1]
    tabs = list(first_entry.paragraph_format.tab_stops)
    assert tabs, "TOC entry has no tab stop"
    right_dotted = [
        t for t in tabs
        if t.alignment == WD_TAB_ALIGNMENT.RIGHT and t.leader == WD_TAB_LEADER.DOTS
    ]
    assert right_dotted, "TOC entry lacks a right dot-leader tab"


def test_toc_entry_spacing_matches_reference(rich):
    """TOC entry spacing mirrors the reference `toc N` STYLE definitions
    (examples/NIEHS-10 styles.xml), NOT a reverse-engineered exact line height:
    NO line-spacing override (each entry snaps to the section docGrid, ~18pt),
    `toc 1` carries 6pt `before` to group the section blocks, and `toc 2`/`toc 3`
    carry no spacing.  An earlier build forced a 25.9pt EXACT line to match the
    rendered pitch, which diverged from the reference's grid-driven style."""
    doc = _open(generate_docx(rich))
    styles = {n: doc.styles[n].paragraph_format for n in ("TOC 1", "TOC 2", "TOC 3")}
    for name, pf in styles.items():
        # No forced line height — spacing comes from the docGrid (like the ref).
        assert pf.line_spacing is None, f"{name} should have no line override"
    # toc 1 groups blocks with 6pt before; deeper levels carry none.
    assert styles["TOC 1"].space_before == Pt(6)
    assert styles["TOC 2"].space_before is None
    assert styles["TOC 3"].space_before is None
    # Reference `toc N` indents (twips): left/hanging per level, and a constant
    # 0.5" (720 twip) RIGHT indent on every level that reserves the page-number
    # column so long titles wrap inside the text area (the appendix-wrap fix).
    from docx.shared import Twips
    assert styles["TOC 1"].left_indent == Twips(360)
    assert styles["TOC 2"].left_indent == Twips(792)
    assert styles["TOC 3"].left_indent == Twips(1296)
    for name in ("TOC 1", "TOC 2", "TOC 3"):
        assert styles[name].right_indent == Twips(720), f"{name} needs the right indent"


def test_yaml_page_breaks_land_as_page_break_before(rich):
    """Pagination is declared in the template `styles` block as `break_before:
    page` per node id (NOT structural page-break nodes) and lands as a direct
    `pageBreakBefore` on each target node's first paragraph — the reference's
    mechanism, which composes idempotently with the dotx's own style breaks.

    Targets whose STYLE does not auto-break rely on this entirely (TOC, About,
    Publication, Tables 3/5/6, appendices); the style-covered ones (Peer Review,
    Abstract, Results, Summary, References) also carry it for cross-surface
    parity.  Tables the reference lets flow (2/4/7/8) must NOT break."""
    doc = _open(generate_docx(rich))
    broken = {p.text.strip() for p in doc.paragraphs
              if p.paragraph_format.page_break_before}
    # Must start a new page.
    for t in ("Table of Contents", "About This Report", "Publication Details",
              "Peer Review", "Abstract", "Results", "Summary", "References"):
        assert t in broken, f"{t!r} should carry pageBreakBefore"
    # Body apical tables 3/5/6 break; 4 flows.
    assert any(s.startswith("Table") and "Liver Weights" in s for s in broken)      # T3
    assert any(s.startswith("Table") and "Hematology" in s for s in broken)         # T5
    assert any(s.startswith("Table") and "Hormone" in s for s in broken)            # T6
    assert not any(s.startswith("Table") and "Clinical Chemistry" in s for s in broken)  # T4 flows
    # Appendices each start a new page.  The heading run text is the BARE
    # descriptive title (the 4-05_Appendix_Head_1 numbered list supplies the
    # "Appendix A." prefix), so match on the title, not the letter prefix.
    assert "Internal Dose Assessment" in broken
    # No leftover standalone empty <w:br type=page> paragraphs from the old
    # page-break NODES (only the title-page end-break remains).
    empties = [
        p for p in doc.paragraphs
        if not p.text.strip()
        and any(b.get(qn("w:type")) == "page" for b in p._p.iter(qn("w:br")))
    ]
    assert len(empties) <= 1, f"unexpected standalone page-break paragraphs: {len(empties)}"


# ---------------------------------------------------------------------------
# Tables list — a native Table-of-Figures FIELD (same field class as the TOC),
# collecting body captions styled 0-25_Table_Title; body captions carry a SEQ
# auto-number.  Titles are chemical-interpolated (reused from the body captions).
# ---------------------------------------------------------------------------

def _tables_list_paras(doc):
    """The `table of figures` entry paragraphs of the front-matter Tables list."""
    ti = next(i for i, p in enumerate(doc.paragraphs) if p.text.strip() == "Tables")
    out = []
    for p in doc.paragraphs[ti + 1:]:
        if p.style.name != "table of figures":
            break
        out.append(p)
    return out


def test_tables_list_is_a_table_of_figures_field(rich):
    """The Tables list is a native Table-of-Figures FIELD — the SAME field class
    as the TOC — that collects body captions styled 0-25_Table_Title, not a plain
    list.  Its instruction is TOC \\h \\z \\t "0-25_Table_Title" \\c, and its
    cached entries are styled `table of figures`."""
    doc = _open(generate_docx(rich))
    instrs = [i.text for i in doc.element.body.findall(".//" + qn("w:instrText"))]
    assert any(i and '\\t "0-25_Table_Title"' in i for i in instrs), (
        f"no Table-of-Figures field instruction in {instrs}"
    )
    entries = _tables_list_paras(doc)
    assert len(entries) >= 8


def test_tables_list_entry_style_matches_reference(rich):
    """The `table of figures` entry style mirrors the reference STYLE
    (examples/NIEHS-10 styles.xml): basedOn Normal with NO spacing override of
    its own — line pitch comes from the section docGrid, exactly as the
    reference's does.  An earlier build forced a 15.9pt exact line + 9.9pt after
    to reverse-engineer the rendered pitch, which diverged from the reference."""
    doc = _open(generate_docx(rich))
    style = doc.styles["table of figures"]
    pf = style.paragraph_format
    assert pf.line_spacing is None, "TOF should have no line override (grid-driven)"
    assert pf.space_after is None, "TOF should carry no space_after of its own"
    # basedOn Normal, like the reference `table of figures` style.
    assert style.base_style is not None and style.base_style.name == "Normal"


def test_body_table_captions_are_seq_numbered(rich):
    """Body table captions use the 0-25_Table_Title style (the TOF collect target)
    and number via a SEQ FIELD, not literal text — so they auto-renumber and are
    collectable by the Tables-list field.  Appendix captions ("Table B-1.") carry a
    letter-prefixed number the arabic SEQ can't express, so they are emitted as
    literal text instead — those are excluded here (see test below)."""
    doc = _open(generate_docx(rich))
    caps = [p for p in doc.paragraphs if p.style.name == "0-25_Table_Title"]
    assert len(caps) >= 8, "no 0-25_Table_Title body captions"
    def _has_seq(p):
        return any(
            (i.text or "").strip().startswith("SEQ Table")
            for i in p._p.findall(".//" + qn("w:instrText"))
        )
    # Body captions ("Table 3. ...") — arabic-numbered — must carry a SEQ field.
    # Appendix captions ("Table B-1. ...") are literal by design.
    body_caps = [p for p in caps if not re.match(r"^Table\s+[A-Za-z]-\d+\.", p.text)]
    assert body_caps, "no arabic-numbered body captions"
    assert all(_has_seq(p) for p in body_caps), "a body caption lacks its SEQ number"


def test_appendix_table_caption_not_double_prefixed(rich):
    """An appendix caption ("Table B-1. ...") is emitted as literal text with NO
    SEQ field — regression guard for the doubled 'Table 1. Table B-1.' bug, where
    the arabic SEQ prepended its own number on top of the letter-prefixed label."""
    doc = _open(generate_docx(rich))
    appendix_caps = [
        p for p in doc.paragraphs
        if p.style.name == "0-25_Table_Title"
        and re.match(r"^Table\s+[A-Za-z]-\d+\.", p.text)
    ]
    for p in appendix_caps:
        # No doubled "Table 1. Table B-1." — exactly one "Table" token leads.
        assert not re.match(r"^Table\s+\d+\.\s*Table\s", p.text), p.text
        # And no SEQ field (letter-prefixed numbers are literal).
        assert not any(
            (i.text or "").strip().startswith("SEQ Table")
            for i in p._p.findall(".//" + qn("w:instrText"))
        ), f"appendix caption should be literal, not SEQ: {p.text!r}"


def test_tables_list_titles_are_chemical_interpolated(rich):
    """Entries reuse the FULL caption the table body renders (chemical / species
    filled from the study) — so a body-weight entry reads 'Summary of Body Weights
    of Male and Female Rats Administered <chemical> for Five Days', matching the
    example documents."""
    doc = _open(generate_docx(rich))
    texts = [p.text for p in _tables_list_paras(doc)]
    # The rich fixture's chemical is "Perfluorohexanesulfonamide"; a full apical
    # caption names it (interpolated from the study, not a frozen literal).
    assert any(
        "Administered Perfluorohexanesulfonamide for Five Days" in t
        and "Summary of Body Weights" in t
        for t in texts
    ), f"no chemical-interpolated body-weight title in: {texts}"


def test_toc_heading_uses_front_matter_style(scaffold):
    """The 'Table of Contents' heading uses a front-matter heading style from the
    template base (1-23_FrontMatter_Head1), not the built-in "TOC Heading" (which
    is absent from the NTP style base).  It is restyled centered/Arial-16 on the
    paragraph; the point here is the style RESOLVES to a real base style."""
    doc = _open(generate_docx(scaffold))
    toc_head = next(p for p in doc.paragraphs if p.text.strip() == "Table of Contents")
    assert toc_head.style.name == "1-23_FrontMatter_Head1"


def test_toc_heading_is_centered_arial_16(scaffold):
    """The Contents header matches the reference 'NTP Contents Heading': CENTERED,
    Arial 16pt bold, 12pt after.  The built-in TOC Heading is basedOn Heading 1
    (left, 14pt), so the handler overrides on the paragraph."""
    from docx.enum.text import WD_ALIGN_PARAGRAPH as _AL
    doc = _open(generate_docx(scaffold))
    h = next(p for p in doc.paragraphs if p.text.strip() == "Table of Contents")
    assert h.alignment == _AL.CENTER
    assert h.paragraph_format.space_after == Pt(12)
    run = h.runs[0]
    assert run.font.name == "Arial"
    assert run.font.size == Pt(16)
    assert run.font.bold is True


def test_body_headings_are_collectable_by_the_field(scaffold):
    """The field collects by outline level, so body headings must carry one.
    On the template-base path body headings use the NTP native heading styles
    (3-02a/3-03a/3-04a_Head*_NoNumber), which carry outlineLvl 0/1/2 — assert
    they are present so the field has something to collect."""
    doc = _open(generate_docx(scaffold))
    ntp_heads = {"3-02a_Head1_NoNumber", "3-03a_Head2_NoNumber", "3-04a_Head3_NoNumber"}
    collectable = [
        p for p in doc.paragraphs
        if p.style and (p.style.name in ntp_heads
                        or p.style.name in ("Heading 1", "Heading 2", "Heading 3"))
    ]
    assert len(collectable) >= 10


def test_no_field_no_dirty_flag():
    """A document with no field must NOT set updateFields (the flag is scoped to
    the field's presence, detected from the body, not always-on)."""
    from rendering.docx_generator import _build_style_skeleton
    from docx import Document as _Doc
    # A hand-built doc with a paragraph but no field: _mark_fields_dirty is only
    # called by generate_docx when a fldChar exists, so exercise that guard.
    doc = _Doc()
    _build_style_skeleton(doc)
    doc.add_paragraph("no fields here")
    assert not doc.element.body.findall(".//" + qn("w:fldChar"))


def test_update_fields_is_in_schema_order(scaffold):
    """updateFields must sit at its CT_Settings position (before compat/rsids),
    NOT prepended — an out-of-sequence settings child is silently dropped on load
    (the same trap pgNumType documents), which would leave the TOC field never
    updating.  Assert it precedes its schema successors."""
    doc = _open(generate_docx(scaffold))
    kids = [c.tag.split("}")[-1] for c in doc.settings.element]
    assert "updateFields" in kids
    ui = kids.index("updateFields")
    # Every successor that is present must come AFTER updateFields.
    for succ in ("compat", "rsids", "mathPr", "themeFontLang", "docId"):
        if succ in kids:
            assert kids.index(succ) > ui, f"{succ} must follow updateFields"
    # And nothing that must PRECEDE it (e.g. savePreviewPicture) comes after.
    if "savePreviewPicture" in kids:
        assert kids.index("savePreviewPicture") < ui


def test_footer_has_exactly_one_page_field_per_section(scaffold):
    """The body section's footer is linked-to-previous (shared element); the
    generator must not append a SECOND PAGE field to it — a doubled field renders
    the number twice ('iii' → 'iiiiii').  Every section footer carries exactly
    one PAGE field."""
    doc = _open(generate_docx(scaffold))
    for sec in doc.sections:
        instrs = [
            e.text for e in sec.footer.paragraphs[0]._p.findall(".//" + qn("w:instrText"))
        ]
        pages = [i for i in instrs if i and i.strip() == "PAGE"]
        assert len(pages) == 1, f"expected 1 PAGE field, found {len(pages)}"
