r"""
test_docx_generator.py — smoke + structural tests for docx_generator (ADR-0008
Option B, the third render surface).

What this proves
----------------
  - generate_docx returns bytes that python-docx can re-open (a valid .docx).
  - The document has the expected structure: the cover title line, section
    headings from DOCUMENT_TREE, roman→arabic two-section page numbering, and
    at least one rendered table.
  - Rich session data (loaded from the DTXSID50469320 session via the same
    load_session_data path the LaTeX export uses) renders its apical / genomics
    / BMD-summary tables — the shared render_common EXTRACT plans the docx
    handlers consume produce real Word tables, not just placeholders.
  - The dispatch table covers every registered node type (the import-time
    assert_dispatch_covers has teeth — re-checked here explicitly).

What this does NOT prove
------------------------
  - Visual fidelity in Word / LibreOffice — that's a manual review step.
"""

from io import BytesIO
from pathlib import Path

import pytest
from docx import Document
from docx.shared import Inches, Pt

from docx_generator import _DISPATCH, generate_docx
from latex_export import load_session_data
from render_common import RENDERABLE_NODE_TYPES
from report_data import scaffold_report_data


REPO_ROOT = Path(__file__).resolve().parents[2]
SESSION_DTXSID = "DTXSID50469320"
SESSION_DIR = REPO_ROOT / "sessions" / SESSION_DTXSID


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def scaffold() -> dict:
    """The full NIEHS scaffold — complete structure, placeholder content."""
    return scaffold_report_data(
        chemical_name="Perfluorohexanesulfonamide",
        casrn="41997-13-1",
        dtxsid=SESSION_DTXSID,
    )


@pytest.fixture(scope="module")
def rich() -> dict:
    """
    A content-rich, render-ready data dict from the real DTXSID50469320 session
    — the SAME load_session_data path the LaTeX/Overleaf export uses, so this is
    a valid render INPUT (unlike the marshal_rich fixture, which is a marshal
    OUTPUT and not shaped for the renderers).
    """
    if not SESSION_DIR.exists():
        pytest.skip(f"session {SESSION_DTXSID} not present")
    return load_session_data(
        SESSION_DTXSID,
        chemical_name="Perfluorohexanesulfonamide",
        casrn="41997-13-1",
    )


def _open(docx_bytes: bytes) -> Document:
    """Re-open generated bytes as a Document (fails if the .docx is invalid)."""
    return Document(BytesIO(docx_bytes))


def _all_text(doc: Document) -> str:
    """Every paragraph's text joined — for substring assertions."""
    return "\n".join(p.text for p in doc.paragraphs)


# ---------------------------------------------------------------------------
# Structural smoke
# ---------------------------------------------------------------------------

def test_dispatch_covers_every_registered_type():
    """Every canonical node type has a Word emitter (import-time guarantee)."""
    assert set(_DISPATCH) == set(RENDERABLE_NODE_TYPES)


def test_generates_valid_docx(scaffold):
    """Output is bytes that python-docx can re-open."""
    out = generate_docx(scaffold)
    assert isinstance(out, bytes) and len(out) > 0
    doc = _open(out)  # raises if the OOXML is malformed
    assert len(doc.paragraphs) > 0


def test_cover_title_line_present(scaffold):
    """The cover renders the NIEHS title line + the chemical name."""
    doc = _open(generate_docx(scaffold))
    text = _all_text(doc)
    assert "NIEHS Report on the" in text
    assert "Perfluorohexanesulfonamide" in text


def test_section_headings_present(scaffold):
    """Headings derived from DOCUMENT_TREE appear as Word heading styles."""
    doc = _open(generate_docx(scaffold))
    heading_texts = [
        p.text for p in doc.paragraphs if (p.style and p.style.name.startswith("Heading"))
    ]
    joined = "\n".join(heading_texts)
    assert "Background" in joined
    assert heading_texts, "no heading-styled paragraphs were emitted"


def test_two_sections_with_roman_then_arabic_numbering(scaffold):
    """
    Front matter is lower-roman, the body restarts at arabic 1 — a section
    break with two distinct <w:pgNumType> formats.
    """
    doc = _open(generate_docx(scaffold))
    assert len(doc.sections) == 2
    fmts = []
    for section in doc.sections:
        pgNumType = section._sectPr.find(
            "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}pgNumType"
        )
        assert pgNumType is not None
        fmts.append(pgNumType.get(
            "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}fmt"
        ))
    assert fmts == ["lowerRoman", "decimal"]


def test_has_tables(scaffold):
    """At least the sample-counts / roster tables render as Word tables."""
    doc = _open(generate_docx(scaffold))
    assert len(doc.tables) > 0


# ---------------------------------------------------------------------------
# Reference typography — the measured NIEHS spec is bound onto the base styles
# (see docx_generator Constants + _build_style_skeleton).  These lock the fonts
# and geometry so a regression in the style sheet fails loudly.
# ---------------------------------------------------------------------------

def test_body_style_is_times_12pt(scaffold):
    """Normal (the body/base style) is Times New Roman 12pt — the reference body."""
    doc = _open(generate_docx(scaffold))
    normal = doc.styles["Normal"]
    assert normal.font.name == "Times New Roman"
    assert normal.font.size == Pt(12)


def test_heading_styles_are_arial_bold_sized(scaffold):
    """Headings are Arial Bold at the measured sizes (H1 17, H2 15, H3 13pt)."""
    doc = _open(generate_docx(scaffold))
    expected = {1: 17, 2: 15, 3: 13}
    for level, pt in expected.items():
        style = doc.styles[f"Heading {level}"]
        assert style.font.name == "Arial", f"Heading {level} font"
        assert style.font.bold is True, f"Heading {level} bold"
        assert style.font.size == Pt(pt), f"Heading {level} size"


def test_running_header_style_is_times_12pt(scaffold):
    """The running header rides on the Header style — Times New Roman 12pt."""
    doc = _open(generate_docx(scaffold))
    header = doc.styles["Header"]
    assert header.font.name == "Times New Roman"
    assert header.font.size == Pt(12)


def test_section_margins_are_one_inch(scaffold):
    """US-Letter with 1" margins all round (the reference trim)."""
    doc = _open(generate_docx(scaffold))
    for section in doc.sections:
        assert section.left_margin == Inches(1)
        assert section.right_margin == Inches(1)
        assert section.top_margin == Inches(1)
        assert section.bottom_margin == Inches(1)


def test_table_cells_render_below_body_size(scaffold):
    """
    Table cell runs are set to the table size (10pt), one step below the 12pt
    body — so dense tables don't inherit the body size.  Header cells are Arial.
    """
    doc = _open(generate_docx(scaffold))
    # Find a table with a populated data row + header.
    for t in doc.tables:
        if len(t.rows) < 2 or not t.rows[0].cells[0].paragraphs[0].runs:
            continue
        hrun = t.rows[0].cells[0].paragraphs[0].runs[0]
        assert hrun.font.size == Pt(10)
        assert hrun.font.name == "Arial"
        # A data-row run (skip merged sex-separator rows, which have one cell).
        for r in t.rows[1:]:
            runs = r.cells[-1].paragraphs[0].runs
            if runs:
                assert runs[0].font.size == Pt(10)
                return
    pytest.skip("no populated table with header + data row found")


# ---------------------------------------------------------------------------
# Per-node layout styling — the docx twin of the CSS/LaTeX translators.  A
# `styles` block with per-type/per-instance specs applies to the paragraphs the
# matching node emitted, overlaying the base Normal/Heading styles.
# ---------------------------------------------------------------------------

def test_per_type_layout_style_applies_to_matching_nodes(scaffold):
    """A `types` entry restyles every node of that type (font/size/color)."""
    data = dict(scaffold)
    data["layout_style"] = {
        "types": {"narrative": {"font": "Georgia", "font_size": "14pt",
                                "color": "#cc0000"}}
    }
    doc = _open(generate_docx(data))
    styled = [
        r for p in doc.paragraphs for r in p.runs
        if r.font.name == "Georgia" and r.font.size == Pt(14)
    ]
    assert styled, "no narrative runs picked up the per-type font/size"
    assert str(styled[0].font.color.rgb) == "CC0000"


def test_instance_layer_wins_over_type_layer_in_docx(scaffold):
    """An `instances` entry overrides the `types` layer for one node id."""
    data = dict(scaffold)
    data["layout_style"] = {
        "types": {"narrative": {"weight": "normal"}},
        "instances": {"background": {"weight": "bold"}},
    }
    doc = _open(generate_docx(data))
    # The Background heading run must be bold (instance layer), proving the
    # instance override reached the docx surface.
    bg = [p for p in doc.paragraphs if p.text.strip() == "Background"]
    assert bg and any(r.font.bold for r in bg[0].runs)


def test_no_layout_style_is_a_noop(scaffold):
    """A document with no `layout_style` renders (base styles only, no crash)."""
    data = dict(scaffold)
    data.pop("layout_style", None)
    doc = _open(generate_docx(data))
    assert len(doc.paragraphs) > 0


def test_document_level_block_drives_page_and_base_fonts(scaffold):
    """The styles.document block overrides page geometry + base body/header fonts."""
    data = dict(scaffold)
    data["layout_style"] = {"document": {
        "page_width": "8.27in", "page_height": "11.69in",   # A4
        "margin_left": "1.25in",
        "default_font": "Palatino Linotype", "default_font_size": "11pt",
        "header_font": "Cambria",
    }}
    doc = _open(generate_docx(data))
    s = doc.sections[0]
    assert round(s.page_width.inches, 2) == 8.27
    assert round(s.page_height.inches, 2) == 11.69
    assert round(s.left_margin.inches, 2) == 1.25
    assert doc.styles["Normal"].font.name == "Palatino Linotype"
    assert doc.styles["Normal"].font.size == Pt(11)
    assert doc.styles["Header"].font.name == "Cambria"


def test_absent_document_block_uses_reference_constants(scaffold):
    """No document block ⇒ the measured reference defaults (US-Letter, Times 12)."""
    data = dict(scaffold)
    data.pop("layout_style", None)
    doc = _open(generate_docx(data))
    s = doc.sections[0]
    assert round(s.page_width.inches, 2) == 8.5
    assert round(s.page_height.inches, 2) == 11.0
    assert doc.styles["Normal"].font.name == "Times New Roman"
    assert doc.styles["Normal"].font.size == Pt(12)


# ---------------------------------------------------------------------------
# Rich-data rendering — the shared EXTRACT plans produce real tables
# ---------------------------------------------------------------------------

def test_rich_data_renders_at_least_as_many_tables_as_scaffold(scaffold, rich):
    """
    A content-rich session dict must render at least as many tables as the
    placeholder scaffold, and a healthy number overall — proof the apical /
    genomics / BMD-summary plans actually emit Word tables when data is present.
    """
    scaffold_doc = _open(generate_docx(scaffold))
    rich_doc = _open(generate_docx(rich))
    assert len(rich_doc.tables) >= len(scaffold_doc.tables)
    assert len(rich_doc.tables) >= 5


def test_rich_data_renders_without_error(rich):
    """The full rich fixture renders end-to-end and re-opens cleanly."""
    doc = _open(generate_docx(rich))
    assert len(doc.paragraphs) > 0
    # The running header falls back through running_header/title — the rich
    # fixture sets a title, so it must not be the bare placeholder.
    assert _all_text(doc)
