r"""
test_docx_generator.py — smoke + structural tests for docx_generator (ADR-0008
Option B, the third render surface).

What this proves
----------------
  - generate_docx returns bytes that python-docx can re-open (a valid .docx).
  - The document has the expected structure: the cover title line, section
    headings from DOCUMENT_TREE, roman→arabic two-section page numbering, and
    at least one rendered table.
  - Rich session data (loaded from the DTXSID50469320 session via the same
    load_session_data path the LaTeX export uses) renders its apical / genomics
    / BMD-summary tables — the shared render_common EXTRACT plans the docx
    handlers consume produce real Word tables, not just placeholders.
  - The dispatch table covers every registered node type (the import-time
    assert_dispatch_covers has teeth — re-checked here explicitly).

What this does NOT prove
------------------------
  - Visual fidelity in Word / LibreOffice — that's a manual review step.
"""

from io import BytesIO
from pathlib import Path

import pytest
from docx import Document

from docx_generator import _DISPATCH, generate_docx
from latex_export import load_session_data
from render_common import RENDERABLE_NODE_TYPES
from report_data import scaffold_report_data


REPO_ROOT = Path(__file__).resolve().parents[2]
SESSION_DTXSID = "DTXSID50469320"
SESSION_DIR = REPO_ROOT / "sessions" / SESSION_DTXSID


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def scaffold() -> dict:
    """The full NIEHS scaffold — complete structure, placeholder content."""
    return scaffold_report_data(
        chemical_name="Perfluorohexanesulfonamide",
        casrn="41997-13-1",
        dtxsid=SESSION_DTXSID,
    )


@pytest.fixture(scope="module")
def rich() -> dict:
    """
    A content-rich, render-ready data dict from the real DTXSID50469320 session
    — the SAME load_session_data path the LaTeX/Overleaf export uses, so this is
    a valid render INPUT (unlike the marshal_rich fixture, which is a marshal
    OUTPUT and not shaped for the renderers).
    """
    if not SESSION_DIR.exists():
        pytest.skip(f"session {SESSION_DTXSID} not present")
    return load_session_data(
        SESSION_DTXSID,
        chemical_name="Perfluorohexanesulfonamide",
        casrn="41997-13-1",
    )


def _open(docx_bytes: bytes) -> Document:
    """Re-open generated bytes as a Document (fails if the .docx is invalid)."""
    return Document(BytesIO(docx_bytes))


def _all_text(doc: Document) -> str:
    """Every paragraph's text joined — for substring assertions."""
    return "\n".join(p.text for p in doc.paragraphs)


# ---------------------------------------------------------------------------
# Structural smoke
# ---------------------------------------------------------------------------

def test_dispatch_covers_every_registered_type():
    """Every canonical node type has a Word emitter (import-time guarantee)."""
    assert set(_DISPATCH) == set(RENDERABLE_NODE_TYPES)


def test_generates_valid_docx(scaffold):
    """Output is bytes that python-docx can re-open."""
    out = generate_docx(scaffold)
    assert isinstance(out, bytes) and len(out) > 0
    doc = _open(out)  # raises if the OOXML is malformed
    assert len(doc.paragraphs) > 0


def test_cover_title_line_present(scaffold):
    """The cover renders the NIEHS title line + the chemical name."""
    doc = _open(generate_docx(scaffold))
    text = _all_text(doc)
    assert "NIEHS Report on the" in text
    assert "Perfluorohexanesulfonamide" in text


def test_section_headings_present(scaffold):
    """Headings derived from DOCUMENT_TREE appear as Word heading styles."""
    doc = _open(generate_docx(scaffold))
    heading_texts = [
        p.text for p in doc.paragraphs if (p.style and p.style.name.startswith("Heading"))
    ]
    joined = "\n".join(heading_texts)
    assert "Background" in joined
    assert heading_texts, "no heading-styled paragraphs were emitted"


def test_two_sections_with_roman_then_arabic_numbering(scaffold):
    """
    Front matter is lower-roman, the body restarts at arabic 1 — a section
    break with two distinct <w:pgNumType> formats.
    """
    doc = _open(generate_docx(scaffold))
    assert len(doc.sections) == 2
    fmts = []
    for section in doc.sections:
        pgNumType = section._sectPr.find(
            "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}pgNumType"
        )
        assert pgNumType is not None
        fmts.append(pgNumType.get(
            "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}fmt"
        ))
    assert fmts == ["lowerRoman", "decimal"]


def test_has_tables(scaffold):
    """At least the sample-counts / roster tables render as Word tables."""
    doc = _open(generate_docx(scaffold))
    assert len(doc.tables) > 0


# ---------------------------------------------------------------------------
# Rich-data rendering — the shared EXTRACT plans produce real tables
# ---------------------------------------------------------------------------

def test_rich_data_renders_at_least_as_many_tables_as_scaffold(scaffold, rich):
    """
    A content-rich session dict must render at least as many tables as the
    placeholder scaffold, and a healthy number overall — proof the apical /
    genomics / BMD-summary plans actually emit Word tables when data is present.
    """
    scaffold_doc = _open(generate_docx(scaffold))
    rich_doc = _open(generate_docx(rich))
    assert len(rich_doc.tables) >= len(scaffold_doc.tables)
    assert len(rich_doc.tables) >= 5


def test_rich_data_renders_without_error(rich):
    """The full rich fixture renders end-to-end and re-opens cleanly."""
    doc = _open(generate_docx(rich))
    assert len(doc.paragraphs) > 0
    # The running header falls back through running_header/title — the rich
    # fixture sets a title, so it must not be the bare placeholder.
    assert _all_text(doc)
